L = {}
STL = {}

L["font.1"] = "LondonBetween"
L["font.2"] = "Myriad Pro"
L["font.3"] = "HD44780A00 5x8"

STL["tier.1"] = "4Consumer"
STL["tier.2"] = "3Security"
STL["tier.3"] = "2Operator"
STL["tier.4"] = "1Elite"
STL["tier.spec"] = "9Special"
STL["type.sidearm"] = "1Sidearm"
STL["type.machine_pistol"] = "2Machine Pistol"
STL["type.submachine_gun"] = "3Submachine Gun"
STL["type.assault_rifle"] = "4Assault Rifle"
STL["type.machine_gun"] = "4Machine Gun"
STL["type.shotgun"] = "5Shotgun"
STL["type.sporter_carbine"] = "5Sporter Carbine"
STL["type.precision_rifle"] = "6Precision Rifle"
STL["type.sniper_rifle"] = "7Sniper Rifle"
STL["type.melee_weapon"] = "8Melee Weapon"
STL["type.equipment"] = "9Equipment"
STL["type.throwable"] = "9Throwable"

STL["slot.optic"] = "Optic"
STL["slot.muzzle"] = "Muzzle"
STL["slot.tactical"] = "Tactical"
STL["slot.accessory"] = "Accessory"
STL["slot.bolt"] = "Bolt"
STL["slot.trigger"] = "Trigger"
STL["slot.ammo"] = "Ammo"
STL["slot.perk"] = "Perk"
STL["slot.melee_tech"] = "Technique"
STL["slot.melee_spec"] = "Special"


L["tier.1"] = "Consumer"
L["tier.2"] = "Security"
L["tier.3"] = "Operator"
L["tier.4"] = "Elite"
L["tier.spec"] = "Special"
L["type.sidearm"] = "Sidearm"
L["type.machine_pistol"] = "Machine Pistol"
L["type.submachine_gun"] = "Submachine Gun"
L["type.assault_rifle"] = "Assault Rifle"
L["type.machine_gun"] = "Machine Gun"
L["type.shotgun"] = "Shotgun"
L["type.sporter_carbine"] = "Sporter Carbine"
L["type.precision_rifle"] = "Precision Rifle"
L["type.sniper_rifle"] = "Sniper Rifle"
L["type.melee_weapon"] = "Melee Weapon"
L["type.equipment"] = "Equipment"
L["type.throwable"] = "Throwable"

L["cust.rating"] = "Rating"
L["cust.stats"] = "Stats"
L["cust.description"] = "DESCRIPTION:"
L["cust.type_tier"] = "{tier} Grade {type}"

L["slot.default"] = "Slot"
L["slot.optic"] = "Optic"
L["slot.muzzle"] = "Muzzle"
L["slot.tactical"] = "Tactical"
L["slot.accessory"] = "Accessory"
L["slot.bolt"] = "Bolt"
L["slot.trigger"] = "Trigger"
L["slot.ammo"] = "Ammo"
L["slot.perk"] = "Perk"
L["slot.melee_tech"] = "Technique"
L["slot.melee_spec"] = "Special"

L["ammo.ti_flashbang"] = "Flashbangs"
L["ammo.ti_thermite"] = "Thermite Grenades"
L["ammo.ti_smoke"] = "Smoke Grenades"
L["ammo.ti_c4"] = "C4 Charges"
L["ammo.ti_gas"] = "CS Gas Grenades"
L["ammo.ti_nuke"] = "Nuclear Devices"
L["ammo.ti_charge"] = "Breaching Charge"
L["ammo.ti_sniper"] = "Anti-Materiel Ammo"

L["rating.score"] = "(Score: {score}/{max})"
L["rating.lethality"] = "Lethality"
L["rating.lethality.desc"] = "How easily and quickly the weapon can take out a single target.\nAffected by Damage and RPM."
L["rating.suppression"] = "Suppression"
L["rating.suppression.desc"] = "How much damage the weapon can output over a long period of time.\nAffected by Damage, RPM, Capacity and Reload Time."
L["rating.range"] = "Range"
L["rating.range.desc"] = "How well the weapon gains or loses damage over long distances.\nAffected by Minimum Range, Maximum Range, and damage falloff."
L["rating.precision"] = "Precision"
L["rating.precision.desc"] = "How accurate the weapon is when firing single shots or short bursts.\nAffected by Spread and various Recoil stats."
L["rating.control"] = "Control"
L["rating.control.desc"] = "How managable the weapon's recoil and spread is under sustained fire.\nAffected by RPM and various Recoil stats."
L["rating.handling"] = "Handling"
L["rating.handling.desc"] = "How quickly this weapon readies from sprinting, aiming and deploying.\nAffected by Aim Down Sights Time, Sprint To Fire Time, and Deploy Time."
L["rating.maneuvering"] = "Maneuvering"
L["rating.maneuvering.desc"] = "How well the weapon performs while moving around and not aiming.\nAffected by Hipfire, Moving and Mid-air Spread, as well as Peeking Penalty.\nIf Free Aim or Sway is enabled, they will also be scored."
L["rating.mobility"] = "Mobility"
L["rating.mobility.desc"] = "How fast the user can move while using this weapon.\nAffected by various Speed stats, such as Sighted Speed."
L["rating.stability"] = "Stability"
L["rating.stability.desc"] = "How much the weapon's point of aim will move around.\nAffected by various Sway stats.\nNOTE: No difference if Sway is disabled in the options."

L["stat.table.stat"] = "STAT"
L["stat.table.base"] = "BASE"
L["stat.table.curr"] = "CURR"
L["stat.table.diff"] = "DIFF"

L["stat.raw_dps"] = "Raw DPS"
L["stat.raw_dps.desc"] = "Calculated damage output of the weapon with no damage falloff.\nDoes not consider hitgroup damage multipliers or armor penetration."
L["stat.min_ttk"] = "Minimum TTK"
L["stat.min_ttk.desc"] = "Calculated time needed to kill a target starting from the second shot.\nAssumes no damage falloff and target has your max health.\nDoes not consider hitgroup damage multipliers."
