L = {}

L["font.1"] = "Microsoft YaHei Bold"
L["font.2"] = "Microsoft YaHei"

L["tier.1"] = "民用"
L["tier.2"] = "警备"
L["tier.3"] = "特遣"
L["tier.4"] = "精英"
L["tier.spec"] = "特殊"
L["type.sidearm"] = "手枪"
L["type.machine_pistol"] = "自动手枪"
L["type.submachine_gun"] = "冲锋枪"
L["type.assault_rifle"] = "突击步枪"
L["type.machine_gun"] = "机枪"
L["type.shotgun"] = "霰弹枪"
L["type.sporter_carbine"] = "射手卡宾枪"
L["type.precision_rifle"] = "精准步枪"
L["type.sniper_rifle"] = "狙击枪"
L["type.melee_weapon"] = "近战武器"
L["type.equipment"] = "装备"
L["type.throwable"] = "投掷物"

L["cust.rating"] = "评分"
L["cust.stats"] = "属性"
L["cust.description"] = "简介："
L["cust.type_tier"] = "{tier}{type}"

L["slot.default"] = "槽位"
L["slot.optic"] = "瞄具"
L["slot.muzzle"] = "枪口"
L["slot.tactical"] = "战术"
L["slot.accessory"] = "附件"
L["slot.bolt"] = "枪栓"
L["slot.trigger"] = "扳机"
L["slot.ammo"] = "弹种"
L["slot.perk"] = "专长"
L["slot.melee_tech"] = "手法"
L["slot.melee_spec"] = "特技"

L["ammo.ti_flashbang"] = "Flashbangs"
L["ammo.ti_thermite"] = "Thermite Grenades"
L["ammo.ti_smoke"] = "Smoke Grenades"
L["ammo.ti_c4"] = "C4 Charges"
L["ammo.ti_gas"] = "CS Gas Grenades"
L["ammo.ti_nuke"] = "Nuclear Devices"
L["ammo.ti_charge"] = "Breaching Charge"
L["ammo.ti_sniper"] = "Anti-Materiel Ammo"

L["rating.score"] = "（得分: {score}/{max}）"
L["rating.lethality"] = "爆发火力"
L["rating.lethality.desc"] = "How easily and quickly the weapon can take out a single target.\nAffected by Damage and RPM."
L["rating.suppression"] = "持续火力"
L["rating.suppression.desc"] = "How much damage the weapon can output over a long period of time.\nAffected by Damage, RPM, Capacity and Reload Time."
L["rating.range"] = "有效射程"
L["rating.range.desc"] = "How well the weapon gains or loses damage over long distances.\nAffected by Minimum Range, Maximum Range, and damage falloff."
L["rating.precision"] = "精准度"
L["rating.precision.desc"] = "How accurate the weapon is when firing single shots or short bursts.\nAffected by Spread and various Recoil stats."
L["rating.control"] = "可控度"
L["rating.control.desc"] = "How managable the weapon's recoil and spread is under sustained fire.\nAffected by RPM and various Recoil stats."
L["rating.handling"] = "手感"
L["rating.handling.desc"] = "How quickly this weapon readies from sprinting, aiming and deploying.\nAffected by Aim Down Sights Time, Sprint To Fire Time, and Deploy Time."
L["rating.maneuvering"] = "机动散射"
L["rating.maneuvering.desc"] = "How well the weapon performs while moving around and not aiming.\nAffected by Hipfire, Moving and Mid-air Spread, as well as Peeking Penalty.\nIf Free Aim or Sway is enabled, they will also be scored."
L["rating.mobility"] = "机动速度"
L["rating.mobility.desc"] = "How fast the user can move while using this weapon.\nAffected by various Speed stats, such as Sighted Speed."
L["rating.stability"] = "稳定性"
L["rating.stability.desc"] = "How much the weapon's point of aim will move around.\nAffected by various Sway stats.\nNOTE: No difference if Sway is disabled in the options."

L["stat.table.stat"] = "属性名"
L["stat.table.base"] = "基础值"
L["stat.table.curr"] = "当前值"
L["stat.table.diff"] = "差别"

L["stat.raw_dps"] = "每秒伤害（理想值）"
L["stat.raw_dps.desc"] = "推算得出的，武器每秒能打出的最高伤害。\n不计算头部和肢体伤害倍率。"
L["stat.min_ttk"] = "击杀耗时（理想值）"
L["stat.min_ttk.desc"] = "推算得出的，武器击杀目标需要的最低时间。\n假设目标无护甲，生命值等同于你的生命上限。\n不计算头部和肢体伤害倍率。"
