L = {} -- Swedish Content Strings by Moka

///////////////////// -- [[ TacRP Base ]] --
-- Weapons
local ws = "tacrp_"
local w = ws .. "ak47"
L["wep." .. w .. ".name.full"] = "FB Beryl 96"
L["wep." .. w .. ".name"] = "Beryl 96"
L["wep." .. w .. ".desc"] = "Easy to handle rifle with low fire rate and recoil."
L["wep." .. w .. ".desc.quote"] = "Despite its looks, it is not an AK."
L["wep." .. w .. ".trivia.manufacturer"] = "FB \"Łucznik\" Radom"
L["wep." .. w .. ".trivia.caliber"] = "5,56 x 45 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "amd65"
L["wep." .. w .. ".name"] = "AMD-65"
L["wep." .. w .. ".desc"] = "Hungarian AK clone with integrated grip and wire stock. High damage, but lower range than most rifles."
L["wep." .. w .. ".trivia.manufacturer"] = "Fegyver- és Gépgyár"
L["wep." .. w .. ".trivia.caliber"] = "7,62 x 39 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "ar15"
L["wep." .. w .. ".name.full"] = "Diemaco AR-15"
L["wep." .. w .. ".name"] = "AR-15"
L["wep." .. w .. ".desc"] = "Customized semi-automatic model of an ubiquitous American rifle. Uses reduced capacity magazines."
L["wep." .. w .. ".desc.quote"] = "\"One of the most beloved and most vilified rifles in the country.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Colt Canada"
L["wep." .. w .. ".trivia.caliber"] = "5,56 x 45 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "as50"
L["wep." .. w .. ".name.full"] = "AI AS50"
L["wep." .. w .. ".name"] = "AS50"
L["wep." .. w .. ".desc"] = "Semi-automatic anti-materiel rifle that can easily decimate any person at any distance.\nEquipped with a 12x scope by default.\nFar too heavy to swing, so bashing is out of the question."
L["wep." .. w .. ".trivia.manufacturer"] = "Accuracy International"
L["wep." .. w .. ".trivia.caliber"] = ".50 BMG"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "aug"
L["wep." .. w .. ".name.full"] = "Steyr AUG A2"
L["wep." .. w .. ".name"] = "AUG A2"
L["wep." .. w .. ".desc"] = "Burst bullpup rifle with a generous magazine capacity and great handling."
L["wep." .. w .. ".trivia.manufacturer"] = "Steyr Arms"
L["wep." .. w .. ".trivia.caliber"] = "5,56 x 45 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "bekas"
L["wep." .. w .. ".name.full"] = "Molot Bekas-16M"
L["wep." .. w .. ".name"] = "Bekas-16M"
L["wep." .. w .. ".desc"] = "Accurate hunting shotgun with low damage."
L["wep." .. w .. ".trivia.manufacturer"] = "Molot"
L["wep." .. w .. ".trivia.caliber"] = "Kaliber 16"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "c4_detonator"
L["wep." .. w .. ".name"] = "C4 Detonator"
L["wep." .. w .. ".desc"] = "Device for touching off C4 charges or other types of remote explosives."
-- L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "civ_amd65"
L["wep." .. w .. ".name.full"] = "Arsenal SAM7SF"
L["wep." .. w .. ".name"] = "SAM7SF"
L["wep." .. w .. ".desc"] = "American semi-automatic AK pattern rifle, customized with an AR-15 style stock and Hungarian handguard. In the interest of public safety, the magazine is limited to 10 rounds."
L["wep." .. w .. ".trivia.manufacturer"] = "Arsenal Inc"
L["wep." .. w .. ".trivia.caliber"] = "7,62 x 39 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention\nModel Edit: Arctic"

w = ws .. "civ_g36k"
L["wep." .. w .. ".name.full"] = "H&K HK243"
L["wep." .. w .. ".name"] = "HK243"
L["wep." .. w .. ".desc"] = "Customized semi-automatic model of an iconic polymer rifle.\nUses reduced capacity magazines."
L["wep." .. w .. ".desc.quote"] = "\"Weapons of war do not belong on our streets!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = "5,56 x 45 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "civ_m320"
L["wep." .. w .. ".name.full"] = "H&K M320LE"
L["wep." .. w .. ".name"] = "M320LE"
L["wep." .. w .. ".desc"] = "Law Enforcement version of the M320 sanctioned for less-lethal munitions. Fires beanbag rounds that incapacitate on direct hit."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = "40 mm Granater"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "civ_mp5"
L["wep." .. w .. ".name.full"] = "H&K HK94"
L["wep." .. w .. ".name"] = "HK94"
L["wep." .. w .. ".desc"] = "Semi-automatic model of a legendary submachine gun.\nUses reduced capacity magazines."
L["wep." .. w .. ".desc.quote"] = "Frequently seen standing in for its military counterpart."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = "9 x 19 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention\nModel Edit: speedonerd\n(it was soooo hard lol)"

w = ws .. "civ_p90"
L["wep." .. w .. ".name.full"] = "FN PS90"
L["wep." .. w .. ".name"] = "PS90"
L["wep." .. w .. ".desc"] = "Semi-automatic variation of a futuristic PDW.\nUses reduced capacity magazines."
L["wep." .. w .. ".desc.quote"] = "\"This is a weapon of terror. It's made to intimidate the enemy.\""
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".trivia.caliber"] = "FN 5,7 x 28 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention\nModel Edit: speedonerd\n(it was soooo hard lol)"

w = ws .. "dsa58"
L["wep." .. w .. ".name.full"] = "DSA SA58 OSW"
L["wep." .. w .. ".name"] = "SA58"
L["wep." .. w .. ".desc"] = "Battle rifle with slow fire rate but very high damage and armor penetration. Has a grippod that provides some stability if deployed."
L["wep." .. w .. ".desc.quote"] = "\"Shut up, clock in and load up.\""
L["wep." .. w .. ".trivia.manufacturer"] = "DS Arms"
L["wep." .. w .. ".trivia.caliber"] = "7,62 x 51 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "ex_ak47"
L["wep." .. w .. ".name"] = "AK-47"
L["wep." .. w .. ".desc"] = "Iconic Soviet assault rifle. A rugged and simple design that inspired countless clones and derivatives."
L["wep." .. w .. ".desc.quote"] = "The quintessential bad guy gun."
L["wep." .. w .. ".trivia.manufacturer"] = "Kalashnikov Concern"
L["wep." .. w .. ".trivia.caliber"] = "7,62 x 39 mm"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta, PoisonHeadcrab, Steelbeast\nTextur: Millenia, IppE, FxDarkloki, Pete\nLjud: CC5, modderfreak, .exe\nAnimationer: Tactical Intervention"

w = ws .. "ex_glock"
L["wep." .. w .. ".name"] = "Glock 17"
L["wep." .. w .. ".desc"] = "Polymer pistol with larger-than-standard capacity and a fast fire rate."
L["wep." .. w .. ".desc.quote"] = "Does not show up on airport metal detectors."
L["wep." .. w .. ".trivia.manufacturer"] = "Glock Ges.m.b.H"
L["wep." .. w .. ".trivia.caliber"] = "9 x 19 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Twinke Masta \nLjud: Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "ex_hecate"
L["wep." .. w .. ".name.full"] = "PGM Hécate II"
L["wep." .. w .. ".name"] = "Hécate II"
L["wep." .. w .. ".desc"] = "Heavy anti-materiel rifle that can kill in one shot.\nEquipped with a 12x scope by default. \nLight enough for swing for melee."
L["wep." .. w .. ".desc.quote"] = "Gun Runner tested, NCR approved."
L["wep." .. w .. ".trivia.manufacturer"] = "PGM Précision"
L["wep." .. w .. ".trivia.caliber"] = ".50 BMG"
L["wep." .. w .. ".credits"] = "Tillgångar: Toby Burnside\nKälla: Fallout 4: New Vegas Project"

w = ws .. "ex_hk45c"
L["wep." .. w .. ".name.full"] = "H&K HK45 Compact"
L["wep." .. w .. ".name"] = "HK45C"
L["wep." .. w .. ".desc"] = "Modern high-caliber pistol with great firepower in a handy package."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = ".45 ACP"
L["wep." .. w .. ".credits"] = "Modell: B0t, Red Crayon\nTexturer: IppE, Grall19\nLjud: DMG, xLongWayHome, Leeroy Newman\nAnimationer: Tactical Intervention"

w = ws .. "ex_m4a1"
L["wep." .. w .. ".name.full"] = "Colt M4A1"
L["wep." .. w .. ".name"] = "M4A1"
L["wep." .. w .. ".desc"] = "A true American classic boasting high fire rate and balanced performance."
L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
L["wep." .. w .. ".trivia.caliber"] = "5,56 x 45 mm"
L["wep." .. w .. ".credits"] = "Modell/Textur: Twinke Masta, DMG\nLjud: Teh Strelok\nAnimationer: Tactical Intervention"

w = ws .. "ex_m1911"
L["wep." .. w .. ".name.full"] = "Colt M1911"
L["wep." .. w .. ".name"] = "M1911"
L["wep." .. w .. ".desc"] = "Surplus pistol from an era before tactical attachments and pistol optics, yet still hits quite hard."
L["wep." .. w .. ".desc.quote"] = "\"Hasta la vista, baby!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
L["wep." .. w .. ".trivia.caliber"] = ".45 ACP"
L["wep." .. w .. ".credits"] = "Modell/Textur: Twinke Masta, DMG\nLjud: xLongWayHome, Strelok, Vunsunta\nAnimationer: Tactical Intervention"

w = ws .. "ex_mac10"
L["wep." .. w .. ".name.full"] = "Ingram MAC-11"
L["wep." .. w .. ".name"] = "MAC-11"
L["wep." .. w .. ".desc"] = "A bullet hose best used for point blank spray-and-pray."
L["wep." .. w .. ".desc.quote"] = "\"Give me the motherfuckin' gun, Tre!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Military Armament Corporation"
L["wep." .. w .. ".trivia.caliber"] = ".380 ACP"
L["wep." .. w .. ".credits"] = "Modell/Textur: Enron\nLjud: Vunsunta,  Erick F\nAnimationer: Tactical Intervention"

w = ws .. "ex_mp9"
L["wep." .. w .. ".name.full"] = "B&T MP9"
L["wep." .. w .. ".name"] = "MP9"
L["wep." .. w .. ".desc"] = "Compact polymer submachine gun packing lots of firepower in a small package."
L["wep." .. w .. ".desc.quote"] = "\"Your right hand comes off?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Brügger & Thomet"
L["wep." .. w .. ".trivia.caliber"] = "9 x 19 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Logger & The Expert \nKälla: Gamebanana"

w = ws .. "ex_stinger"
L["wep." .. w .. ".name.full"] = "FIM-92 Stinger"
L["wep." .. w .. ".name"] = "Stinger"
L["wep." .. w .. ".desc"] = "Homing anti-air missile launcher. High blast damage but limited effect on armored targets.\nRequires a lock-on in order to fire."
L["wep." .. w .. ".desc.quote"] = "\"A cornered fox is more dangerous than a jackal!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Raytheon Missiles and Defense"
L["wep." .. w .. ".trivia.caliber"] = "Infraröd Sökande Robot"
L["wep." .. w .. ".credits"] = "Tillgångar: Modern Warfare 2\nAnimationer: Tactical Intervention"

w = ws .. "ex_ump45"
L["wep." .. w .. ".name.full"] = "H&K UMP45"
L["wep." .. w .. ".name"] = "UMP45"
L["wep." .. w .. ".desc"] = "Boxy SMG developed with low production costs in mind.\nHigh damage up close, but range and rate of fire is low."
L["wep." .. w .. ".desc.quote"] = "\"The fuck are these, cocktail guns?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = ".45 ACP"
L["wep." .. w .. ".credits"] = "Tillgångar: Hellspike, Logger & Cyper \nKälla: Gamebanana"

w = ws .. "ex_usp"
L["wep." .. w .. ".name.full"] = "H&K USP"
L["wep." .. w .. ".name"] = "USP"
L["wep." .. w .. ".desc"] = "Tactical pistol with good damage and range."
L["wep." .. w .. ".desc.quote"] = "\"Man of few words, aren't you?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = ".40 S&W"
L["wep." .. w .. ".credits"] = "Modell: Thanez, Racer445\nTextur: Thanez, fxdarkloki\nLjud: Vunsunta, BlitzBoaR\nAnimationer: Tactical Intervention"

w = ws .. "fp6"
L["wep." .. w .. ".name.full"] = "H&K FABARM FP6"
L["wep." .. w .. ".name"] = "FABARM FP6"
L["wep." .. w .. ".desc"] = "Combat shotgun with high fire rate and capacity."
L["wep." .. w .. ".trivia.manufacturer"] = "FABARM S.p.A."
L["wep." .. w .. ".trivia.caliber"] = "Kaliber 12"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "g36k"
L["wep." .. w .. ".name.full"] = "H&K G36K"
L["wep." .. w .. ".name"] = "G36K"
L["wep." .. w .. ".desc"] = "Assault rifle with high muzzle velocity. Well suited for medium range sustained fire.\nEquipped with a 2x scope by default."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = "5,56 x 45 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "gsr1911"
L["wep." .. w .. ".name.full"] = "SIG 1911 TACOPS"
L["wep." .. w .. ".name"] = "SIG 1911"
L["wep." .. w .. ".desc"] = "High damage pistol with low range and capacity.\nA tactical evolution, or some would call devolution, of a venerable classic."
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer, Inc."
L["wep." .. w .. ".trivia.caliber"] = ".45 ACP"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "hk417"
L["wep." .. w .. ".name.full"] = "H&K HK417"
L["wep." .. w .. ".name"] = "HK417"
L["wep." .. w .. ".desc"] = "Battle rifle with superb damage, fire rate and precision. Capable of automatic fire, although it is very unstable."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = "7,62 x 51 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "k1a"
L["wep." .. w .. ".name.full"] = "Daewoo K1A"
L["wep." .. w .. ".name"] = "K1A"
L["wep." .. w .. ".desc"] = "Burst rifle with minimal recoil and good hip firing accuracy."
L["wep." .. w .. ".trivia.manufacturer"] = "Daewoo Precision"
L["wep." .. w .. ".trivia.caliber"] = "5,56 x 45 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "knife"
L["wep." .. w .. ".name"] = "Flip Knife"
L["wep." .. w .. ".desc"] = "A multi-purpose flip knife, although most of the purposes involving stabbing someone."
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "knife2"
L["wep." .. w .. ".name"] = "Jackal Knife"
L["wep." .. w .. ".desc"] = "Very edgy looking knife. Light, partially skeletized blade makes it faster to swing but do less damage."
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention (Unused)"

w = ws .. "ks23"
L["wep." .. w .. ".name"] = "KS-23"
L["wep." .. w .. ".desc"] = "Made from recycled aircraft gun barrels, this heavy shotgun fires shells with twice the diameter of typical shotshells and can easily tear apart anything it's vaguely pointed at. Able to breach doors."
L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
L["wep." .. w .. ".trivia.caliber"] = "23 x 75 mmR"
L["wep." .. w .. ".credits"] = "Tillgångar: Firearms: Source"

w = ws .. "m1"
L["wep." .. w .. ".name.full"] = "Ruger Mini-14"
L["wep." .. w .. ".name"] = "Mini-14"
L["wep." .. w .. ".desc"] = "Lightweight rifle with no stock or optic mount.\nGood hip-fire accuracy among rifles, but range is low."
L["wep." .. w .. ".desc.quote"] = "\"The one with the gun gets to tell the truth.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Sturm, Ruger & Co."
L["wep." .. w .. ".trivia.caliber"] = ".223 Remington"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "m4"
L["wep." .. w .. ".name.full"] = "Diemaco C8A1"
L["wep." .. w .. ".name"] = "C8A1"
L["wep." .. w .. ".desc"] = "A close cousin to the classic American rifle with a slower but more controllable rate of fire."
L["wep." .. w .. ".desc.quote"] = "Green and very, very mean."
L["wep." .. w .. ".trivia.manufacturer"] = "Colt Canada"
L["wep." .. w .. ".trivia.caliber"] = "5,56 x 45 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "m4star10"
L["wep." .. w .. ".name.full"] = "Benelli M4 Super 90"
L["wep." .. w .. ".name"] = "M4 Super 90"
L["wep." .. w .. ".desc"] = "Semi-automatic shotgun with very high damage output. Reloading may be a chore."
L["wep." .. w .. ".desc.quote"] = "There's nothing seven 12 Gauge shotshells can't solve."
L["wep." .. w .. ".trivia.manufacturer"] = "Benelli Armi S.p.A."
L["wep." .. w .. ".trivia.caliber"] = "Kaliber 12"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "m14"
L["wep." .. w .. ".name.full"] = "Springfield M1A"
L["wep." .. w .. ".name"] = "M1A"
L["wep." .. w .. ".desc"] = "Semi-automatic rifle with a lethal headshot.\nEquipped with a 6x scope by default."
L["wep." .. w .. ".desc.quote"] = "\"This my rifle! There are many like it, but this one is mine!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Springfield Armory"
L["wep." .. w .. ".trivia.caliber"] = "7,62 x 51 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "m320"
L["wep." .. w .. ".name.full"] = "H&K M320"
L["wep." .. w .. ".name"] = "M320"
L["wep." .. w .. ".desc"] = "Grenade launcher capable of firing a variety of payloads."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = "40 mm Granater"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "medkit"
L["wep." .. w .. ".name"] = "First Aid Kit"
L["wep." .. w .. ".desc"] = "Compact pack of medical supplies for treating wounds."
L["wep." .. w .. ".desc.quote"] = "\"Keep still, let me patch you up.\""
L["wep." .. w .. ".credits"] = "Modell/Textur: Left 4 Dead 2\nAnimationer: Arqu"

w = ws .. "mg4"
L["wep." .. w .. ".name.full"] = "H&K MG4"
L["wep." .. w .. ".name"] = "MG4"
L["wep." .. w .. ".desc"] = "Machine gun with huge volume of fire."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = "5,56 x 45 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "mp5"
L["wep." .. w .. ".name.full"] = "H&K MP5A3"
L["wep." .. w .. ".name"] = "MP5A3"
L["wep." .. w .. ".desc"] = "Well-balanced submachine gun known for its precision."
L["wep." .. w .. ".desc.quote"] = "\"Now I have a machine gun. Ho, ho, ho.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = "9 x 19 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "mp7"
L["wep." .. w .. ".name.full"] = "H&K MP7"
L["wep." .. w .. ".name"] = "MP7"
L["wep." .. w .. ".desc"] = "PDW with superb handling and close range effectiveness. High velocity rounds retain effectiveness at range and pierces armor easily."
L["wep." .. w .. ".desc.quote"] = "\"You forgot to cock it, muthafucka!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = "HK 4.6 x 30 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "mr96"
L["wep." .. w .. ".name.full"] = "Manurhin MR96"
L["wep." .. w .. ".name"] = "MR96"
L["wep." .. w .. ".desc"] = "Magnum revolver with good handling and stopping power. Accurate, but hard to fire rapidly."
L["wep." .. w .. ".trivia.manufacturer"] = "Chapuis Armes"
L["wep." .. w .. ".trivia.caliber"] = ".357 Magnum"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "mtx_dual"
L["wep." .. w .. ".name"] = "Dual MTX"
L["wep." .. w .. ".desc"] = "An indulgent pair of high capacity, high damage, high quality compact pistols."
L["wep." .. w .. ".desc.quote"] = "With firepower like this, who needs aiming?"
L["wep." .. w .. ".trivia.manufacturer"] = "Detonics Defense"
L["wep." .. w .. ".trivia.caliber"] = ".45 ACP"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "nade_charge"
L["wep." .. w .. ".name.full"] = "Breaching Charge"

w = ws .. "nade_flashbang"
L["wep." .. w .. ".name.full"] = "Chockgranat"

w = ws .. "nade_frag"
L["wep." .. w .. ".name.full"] = "Splittergranat"

w = ws .. "nade_gas"
L["wep." .. w .. ".name.full"] = "Tårgasgranat"

w = ws .. "nade_heal"
L["wep." .. w .. ".name.full"] = "Medi-Rök Kanister"

w = ws .. "nade_smoke"
L["wep." .. w .. ".name.full"] = "Rökgranat"

w = ws .. "nade_thermite"
L["wep." .. w .. ".name"] = "Termitgranat"

w = ws .. "p90"
L["wep." .. w .. ".name.full"] = "FN P90"
L["wep." .. w .. ".name"] = "P90"
L["wep." .. w .. ".desc"] = "Bullpup PDW with a generous top-loaded magazine and controllable spread. High velocity rounds retain effectiveness at range and pierces armor easily."
L["wep." .. w .. ".desc.quote"] = "\"This is a weapon of war, it's made to kill your enemy.\""
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".trivia.caliber"] = "FN 5,7 x 28 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "p250"
L["wep." .. w .. ".name.full"] = "SIG P250"
L["wep." .. w .. ".name"] = "P250"
L["wep." .. w .. ".desc"] = "Powerful handgun that exchanges capacity for damage and precision."
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer, Inc."
L["wep." .. w .. ".trivia.caliber"] = ".357 SIG"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "p2000"
L["wep." .. w .. ".name.full"] = "H&K P2000"
L["wep." .. w .. ".name"] = "P2000"
L["wep." .. w .. ".desc"] = "Well-rounded, run-of-the-mill police handgun."
L["wep." .. w .. ".desc.quote"] = "\"Raus! Raus! Raus!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".trivia.caliber"] = "9 x 19 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "pdw"
L["wep." .. w .. ".name.full"] = "Knight's Armament Company PDW"
L["wep." .. w .. ".name"] = "KAC PDW"
L["wep." .. w .. ".desc"] = "Carbine caliber subcompact PDW. The perfect blend of rifle and submachine gun."
L["wep." .. w .. ".trivia.manufacturer"] = "Knight's Armament"
L["wep." .. w .. ".trivia.caliber"] = "6mm Whisper"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "riot_shield"
L["wep." .. w .. ".name"] = "Riot Shield"
L["wep." .. w .. ".desc"] = "Lightweight shield. Despite its plastic-looking core, it is capable of stopping almost all rifle caliber rounds.\nAble to sprint and melee attack without compromising the user's safety, but slows down move speed slightly."
L["wep." .. w .. ".credits"] = "Modell/Textur: Tactical Intervention\nAnimationer: Arqu"

w = ws .. "rpg7"
L["wep." .. w .. ".name"] = "RPG-7"
L["wep." .. w .. ".desc"] = "Soviet rocket launcher with powerful explosion.\nSafety fuse prevents point blank detonations."
L["wep." .. w .. ".desc.quote"] = "If you hear someone screaming its name, duck for cover."
L["wep." .. w .. ".trivia.manufacturer"] = "NPO Bazalt"
L["wep." .. w .. ".trivia.caliber"] = "40 mm Raketer"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "sg551"
L["wep." .. w .. ".name.full"] = "SIG SG 551"
L["wep." .. w .. ".name"] = "SG 551"
L["wep." .. w .. ".desc"] = "Assault rifle with all around excellent performance, offset by a lower magazine capacity."
L["wep." .. w .. ".desc.quote"] = "\"No questions, no answers. That's the business we're in.\""
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
L["wep." .. w .. ".trivia.caliber"] = "5,56 x 45 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "skorpion"
L["wep." .. w .. ".name.full"] = "Škorpion vz. 61"
L["wep." .. w .. ".name"] = "Škorpion"
L["wep." .. w .. ".desc"] = "Light machine pistol with good range, recoil and spread."
L["wep." .. w .. ".trivia.manufacturer"] = "CZ Uherský Brod"
L["wep." .. w .. ".trivia.caliber"] = ".32 ACP"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "sphinx"
L["wep." .. w .. ".name.full"] = "Sphinx 2000"
L["wep." .. w .. ".name"] = "Sphinx"
L["wep." .. w .. ".desc"] = "Premium pistol modified to be 3-round burst. High firerate but long burst delay."
L["wep." .. w .. ".trivia.manufacturer"] = "Sphinx Systems"
L["wep." .. w .. ".trivia.caliber"] = "9 x 19 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "spr"
L["wep." .. w .. ".name.full"] = "Remington M700 SPS"
L["wep." .. w .. ".name"] = "R700 SPS"
L["wep." .. w .. ".desc"] = "Medium range hunting rifle with a fast cycle speed.\nEquipped with a 6x scope by default."
L["wep." .. w .. ".trivia.manufacturer"] = "Remington Arms"
L["wep." .. w .. ".trivia.caliber"] = ".308 Winchester"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "superv"
L["wep." .. w .. ".name.full"] = "Kriss Vector"
L["wep." .. w .. ".name"] = "Vector"
L["wep." .. w .. ".desc"] = "Close range SMG with extremely high fire rate and practically no recoil. Low armor penetration, but can chew through it very quickly."
L["wep." .. w .. ".trivia.manufacturer"] = "Kriss USA, Inc."
L["wep." .. w .. ".trivia.caliber"] = "9 x 19 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "tgs12"
L["wep." .. w .. ".name.full"] = "Tomahawk Matador"
L["wep." .. w .. ".name"] = "Matador"
L["wep." .. w .. ".desc"] = "Short barrel pistol grip shotgun. High mobility and recoil, and most effective at close range."
L["wep." .. w .. ".desc.quote"] = "For years, its true identity was a mystery."
L["wep." .. w .. ".trivia.manufacturer"] = "Tomahawk Shotguns"
L["wep." .. w .. ".trivia.caliber"] = "Kaliber 12"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "uratio"
L["wep." .. w .. ".name.full"] = "PGM Ultima Ratio"
L["wep." .. w .. ".name"] = "Ultima Ratio"
L["wep." .. w .. ".desc"] = "Lightweight sniper rifle with good damage and high mobility.\nEquipped with a 10x scope by default."
L["wep." .. w .. ".trivia.manufacturer"] = "PGM Précision"
L["wep." .. w .. ".trivia.caliber"] = "6,5 mm Creedmoor"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "uzi"
L["wep." .. w .. ".name.full"] = "IMI Uzi Pro"
L["wep." .. w .. ".name"] = "Uzi Pro"
L["wep." .. w .. ".desc"] = "Balanced machine pistol with a controllable rate of fire."
L["wep." .. w .. ".trivia.manufacturer"] = "Israel Military Industries"
L["wep." .. w .. ".trivia.caliber"] = "9 x 19 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "vertec"
L["wep." .. w .. ".name.full"] = "Beretta 92FS Vertec"
L["wep." .. w .. ".name"] = "92FS Vertec"
L["wep." .. w .. ".desc"] = "Italian pistol with above average range and accuracy."
L["wep." .. w .. ".desc.quote"] = "\"Yippie ki-yay, motherfucker!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
L["wep." .. w .. ".trivia.caliber"] = "9 x 19 mm"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

w = ws .. "xd45"
L["wep." .. w .. ".name.full"] = "Springfield XD-45"
L["wep." .. w .. ".name"] = "XD-45"
L["wep." .. w .. ".desc"] = "Automatic machine pistol with incredible close range power."
L["wep." .. w .. ".trivia.manufacturer"] = "Springfield Armory"
L["wep." .. w .. ".trivia.caliber"] = ".45 ACP"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

-- Attachments (Non-Bulk)
L["att.melee_spec_charge.name.full"] = "demoknight tf2"
L["att.melee_spec_charge.name"] = "Anfall"
L["att.melee_spec_charge.desc"] = "Avancera med hänsynslöst överge, och ta sönder fysikens lagar också."
L["att.pro.melee_spec_charge1"] = "LADDA OM: Anfall"
L["att.pro.melee_spec_charge2"] = "GÅ + LADDA OM: Välj Anfallsläge"
L["att.pro.melee_spec_charge3"] = "Sänkt Skada under Anfall"
L["att.pro.melee_spec_charge4"] = "Sänkt Självskada"

L["att.melee_spec_lunge.name"] = "Galen"
L["att.melee_spec_lunge.desc"] = "Sänk avståndet och överväldiga dina fiender."
L["att.pro.melee_spec_lunge1"] = "LADDA OM: Longera mot Blickriktning"

L["att.melee_spec_nade.name.full"] = "Bombardär"
L["att.melee_spec_nade.name"] = "Bombare"
L["att.melee_spec_nade.desc"] = "Använd juryriggade kontaktgranater för att krossa någons dag."
L["att.pro.melee_spec_nade1"] = "LADDA OM: Växla Granater"
L["att.pro.melee_spec_nade2"] = "Granater Sprängs vid Kontakt"
L["att.con.melee_spec_nade"] = "Granatskada"

L["att.melee_spec_ninja.name"] = "Ninja"
L["att.melee_spec_ninja.desc"] = "Stör dina fiender och anfall med överraskningsmoment."
L["att.pro.melee_spec_ninja1"] = "LADDA OM: Palm Anfall / Klättra"
L["att.pro.melee_spec_ninja2"] = "LADDA OM: (I luften + Hukad): Dykspark"
L["att.pro.melee_spec_ninja3"] = "LADDA OM: (Hukad): Tillbakahopp"
L["att.pro.melee_spec_ninja4"] = "Tysta Fotsteg"

L["att.melee_spec_scout.name.full"] = "jerma tf2"
L["att.melee_spec_scout.name"] = "Spanare"
L["att.melee_spec_scout.desc"] = "Gräs växer, solen skiner, fåglar flyger, och polar'n - jag skadar folk."
L["att.pro.melee_spec_scout1"] = "LADDA OM: Skjut Boll"
L["att.pro.melee_spec_scout2"] = "Bollens Skada Skalar med Avstånd"
L["att.pro.melee_spec_scout3"] = "Bollen Saktar Ned Måltavlor vid Träff"
L["att.pro.melee_spec_scout4"] = "Multi-Hopp"

L["att.melee_spec_step.name"] = "Lufthopp"
L["att.melee_spec_step.desc"] = "Rörlighetsverktyg som används av blodtörstiga robotar och transkvinnor."
L["att.pro.melee_spec_step1"] = "LADDA OM: Rusa i Rörelseriktning"
L["att.pro.melee_spec_step2"] = "Odödlig under Rusning"

L["att.melee_spec_block.name.full"] = "Högvakt"
L["att.melee_spec_block.name"] = "Vakt"
L["att.melee_spec_block.desc"] = "Försvar är den bästa offensiven. Det är också, av en slump, bästa försvaret."
L["att.pro.melee_spec_block1"] = "ALT-ELD: Blockera Närstridsanfall eller Projektiler"
L["att.pro.melee_spec_block2"] = "Tung Motanfall Efter Lyckad Blockering"

L["att.melee_spec_heavy.name.full"] = "Tunghänt"
L["att.melee_spec_heavy.name"] = "Tung"
L["att.melee_spec_heavy.desc"] = "En klassisk antiterrorist teknik. Slå dem rejält hårt."
L["att.pro.melee_spec_heavy1"] = "ALT-ELD: Tungt Anfall"
L["att.pro.melee_spec_heavy2"] = "Skada i Ryggen"

L["att.melee_tech_nade.name.full"] = "Grenadjär"
L["att.melee_tech_nade.name"] = "Granat"
L["att.melee_tech_nade.desc"] = "Alltid bra att ha något snabbt att kasta."
L["att.pro.melee_tech_nade1"] = "ALT-ELD: Snabbkast"
L["att.pro.melee_tech_nade2"] = "Snabbare Snabbkast"
L["att.pro.melee_tech_nade3"] = "Kasta Stenar"

L["att.melee_tech_throw.name.full"] = "Knivkast"
L["att.melee_tech_throw.name"] = "Kast"
L["att.melee_tech_throw.desc"] = "Ett bartrick har blivit dödligt."
L["att.pro.melee_tech_throw1"] = "ALT-ELD: Kasta Vapnet"
L["att.pro.melee_tech_throw2"] = "Använder Armborstpil Ammo"
L["att.pro.melee_tech_throw3"] = "Bonus Skada i Huvudet"
L["att.pro.melee_tech_throw4"] = "Bonus Skada mot Saktade Ned/Chockade Måltavlor"

-- Attachments (acc)
L["att.acc_bipod.name"] = "Skjutstöd"
L["att.acc_bipod.desc"] = "Vikbart stöd som stabiliserar vapnet när den är utplacerad."

L["att.acc_brace.name"] = "Pistol \"Brace\""
L["att.acc_brace.desc"] = "Förvandlar pistolen till ett gevär. ATF kommer förfölja dig."

L["att.acc_cheekrest.name"] = "Kindskydd"
L["att.acc_cheekrest.desc"] = "Stabiliserar huvudet i siktet och sänker svängningen."

L["att.acc_dual_ergo.name.full"] = "Ergonomiskt Grepp"
L["att.acc_dual_ergo.name"] = "Ergo. Grepp"
L["att.acc_dual_ergo.desc"] = "Räfflat grepp gör det lättare att förflytta sig när man skjuter två vapen."

L["att.acc_dual_quickdraw.name.full"] = "Snabbt Framtagen Hölster"
L["att.acc_dual_quickdraw.name"] = "Framtag"
L["att.acc_dual_quickdraw.desc"] = "Ett par axelbandslösa hölstrar för att snabbt ta fram vapnen och öka laddningstiden."

L["att.acc_dual_skel.name.full"] = "Lätt Grepp"
L["att.acc_dual_skel.name"] = "Lätt Grepp"
L["att.acc_dual_skel.desc"] = "Skelettgrepp gör vapnen lättare att förflytta sig med."

L["att.acc_duffelbag.name"] = "Vapenväska"
L["att.acc_duffelbag.desc"] = "Göm vapnet i en väska så du inte orsakar masspanik."

L["att.acc_ergo.desc"] = "Räfflat grepp gör att gå in och ur siktet snabbare och förflyttning under eld lättare."

L["att.acc_extendedbelt.name.full"] = "Lådeförlängare"
L["att.acc_extendedbelt.name"] = "Lådeförl."
L["att.acc_extendedbelt.desc"] = "Ökar ammo kapaciteten drastiskt i kulsprutor."

L["att.acc_extmag.name.full"] = "Förlängt Magasin"
L["att.acc_extmag.name"] = "Förl. Mag"
L["att.acc_extmag.desc"] = "Ökar lätt vapnets kapacitet."

L["att.acc_foldstock.name"] = "Vikt Kolv"
L["att.acc_foldstock.desc"] = "Håller kolven vikt vilket förbättrar hanteringen drastiskt med kostnad på rekyl."

L["att.acc_foldstock2.name.full"] = "Justerbar Kolv"
L["att.acc_foldstock2.name"] = "Justerbar"
L["att.acc_foldstock2.desc"] = "Korta ned kolven för att öka hanteringen en bit med kostnad på rekyl."

L["att.acc_pad.name"] = "Rekylplatta"
L["att.acc_pad.desc"] = "Gummiplatta utrustat på kolvens ände."

L["att.acc_quickdraw.desc"] = "Axelbandslös hölster med magasinhållare för snabb framtagning och laddning."

L["att.acc_skel.desc"] = "Skelettgrepp gör vapnet snabbare att ta fram och hålla uppe."

L["att.acc_sling.name"] = "Slinga"
L["att.acc_sling.desc"] = "Utrusta en slinga på vapnet som gör det lättare att ta fram och ladda om."

///////////////////// -- [[ InterOps Weapons ]] --
-- Weapons
w = ws .. "REPLACEME"
L["wep." .. w .. ".name.full"] = "REPLACEME"
L["wep." .. w .. ".name"] = "REPLACEME"
L["wep." .. w .. ".desc"] = "REPLACEME"
L["wep." .. w .. ".desc.quote"] = "REPLACEME"
L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"


///////////////////// -- [[ ArmaLite Revolution ]] --
-- Weapons
w = ws .. "REPLACEME"
L["wep." .. w .. ".name.full"] = "REPLACEME"
L["wep." .. w .. ".name"] = "REPLACEME"
L["wep." .. w .. ".desc"] = "REPLACEME"
L["wep." .. w .. ".desc.quote"] = "REPLACEME"
L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

///////////////////// -- [[ Special Delivery ]] --
-- Weapons
w = ws .. "REPLACEME"
L["wep." .. w .. ".name.full"] = "REPLACEME"
L["wep." .. w .. ".name"] = "REPLACEME"
L["wep." .. w .. ".desc"] = "REPLACEME"
L["wep." .. w .. ".desc.quote"] = "REPLACEME"
L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

///////////////////// -- [[ Brute Force ]] --
-- Weapons
w = ws .. "REPLACEME"
L["wep." .. w .. ".name.full"] = "REPLACEME"
L["wep." .. w .. ".name"] = "REPLACEME"
L["wep." .. w .. ".desc"] = "REPLACEME"
L["wep." .. w .. ".desc.quote"] = "REPLACEME"
L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

///////////////////// -- [[ Iron Curtain ]] --
-- Weapons
w = ws .. "REPLACEME"
L["wep." .. w .. ".name.full"] = "REPLACEME"
L["wep." .. w .. ".name"] = "REPLACEME"
L["wep." .. w .. ".desc"] = "REPLACEME"
L["wep." .. w .. ".desc.quote"] = "REPLACEME"
L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

///////////////////// -- [[ Heavy Duty ]] --
-- Weapons
w = ws .. "REPLACEME"
L["wep." .. w .. ".name.full"] = "REPLACEME"
L["wep." .. w .. ".name"] = "REPLACEME"
L["wep." .. w .. ".desc"] = "REPLACEME"
L["wep." .. w .. ".desc.quote"] = "REPLACEME"
L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

///////////////////// -- [[ ExoOps ]] --
-- Weapons
w = ws .. "REPLACEME"
L["wep." .. w .. ".name.full"] = "REPLACEME"
L["wep." .. w .. ".name"] = "REPLACEME"
L["wep." .. w .. ".desc"] = "REPLACEME"
L["wep." .. w .. ".desc.quote"] = "REPLACEME"
L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

///////////////////// -- [[ Scavenger's Spoils ]] --
-- Weapons
w = ws .. "REPLACEME"
L["wep." .. w .. ".name.full"] = "REPLACEME"
L["wep." .. w .. ".name"] = "REPLACEME"
L["wep." .. w .. ".desc"] = "REPLACEME"
L["wep." .. w .. ".desc.quote"] = "REPLACEME"
L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

///////////////////// -- [[ Danger Zone Entities ]] --
-- Weapons
w = ws .. "REPLACEME"
L["wep." .. w .. ".name.full"] = "REPLACEME"
L["wep." .. w .. ".name"] = "REPLACEME"
L["wep." .. w .. ".desc"] = "REPLACEME"
L["wep." .. w .. ".desc.quote"] = "REPLACEME"
L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"

///////////////////// -- [[ One-Offs ]] --
-- Weapons
w = ws .. "REPLACEME"
L["wep." .. w .. ".name.full"] = "REPLACEME"
L["wep." .. w .. ".name"] = "REPLACEME"
L["wep." .. w .. ".desc"] = "REPLACEME"
L["wep." .. w .. ".desc.quote"] = "REPLACEME"
L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
L["wep." .. w .. ".credits"] = "Tillgångar: Tactical Intervention"