L = {} -- Chinese Content Strings by 8Z

///////////////////// -- [[ TacRP Base ]] --
-- Weapons
local ws = "tacrp_"
local w = ws .. "ak47"
-- L["wep." .. w .. ".name.full"] = "FB Beryl 96"
-- L["wep." .. w .. ".name"] = "Beryl 96"
-- L["wep." .. w .. ".desc"] = "Easy to handle rifle with low fire rate and recoil."
-- L["wep." .. w .. ".desc.quote"] = "Despite its looks, it is not an AK."
-- L["wep." .. w .. ".trivia.manufacturer"] = "FB \"Łucznik\" Radom"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "amd65"
-- L["wep." .. w .. ".name"] = "AMD-65"
-- L["wep." .. w .. ".desc"] = "Hungarian AK clone with integrated grip and wire stock. High damage, but lower range than most rifles."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Fegyver- és Gépgyár"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "ar15"
-- L["wep." .. w .. ".name.full"] = "Diemaco AR-15"
-- L["wep." .. w .. ".name"] = "AR-15"
-- L["wep." .. w .. ".desc"] = "Customized semi-automatic model of an ubiquitous American rifle. Uses reduced capacity magazines."
-- L["wep." .. w .. ".desc.quote"] = "\"One of the most beloved and most vilified rifles in the country.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt Canada"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "as50"
-- L["wep." .. w .. ".name.full"] = "AI AS50"
-- L["wep." .. w .. ".name"] = "AS50"
-- L["wep." .. w .. ".desc"] = "Semi-automatic anti-materiel rifle that can easily decimate any person at any distance. \nEquipped with a 12x scope by default. \nFar too heavy to swing, so bashing is out of the question."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Accuracy International"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "aug"
-- L["wep." .. w .. ".name.full"] = "Steyr AUG A2"
-- L["wep." .. w .. ".name"] = "AUG A2"
-- L["wep." .. w .. ".desc"] = "Burst bullpup rifle with a generous magazine capacity and great handling."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Steyr Arms"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "bekas"
-- L["wep." .. w .. ".name.full"] = "Molot Bekas-16M"
-- L["wep." .. w .. ".name"] = "Bekas-16M"
-- L["wep." .. w .. ".desc"] = "Accurate hunting shotgun with low damage."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Molot"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "c4_detonator"
-- L["wep." .. w .. ".name"] = "C4 Detonator"
-- L["wep." .. w .. ".desc"] = "Device for touching off C4 charges or other types of remote explosives."
-- -- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "civ_amd65"
-- L["wep." .. w .. ".name.full"] = "Arsenal SAM7SF"
-- L["wep." .. w .. ".name"] = "SAM7SF"
-- L["wep." .. w .. ".desc"] = "American semi-automatic AK pattern rifle, customized with an AR-15 style stock and Hungarian handguard.\nUses reduced capacity magazines."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Arsenal Inc"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention \nModel Edit: Arctic"

w = ws .. "civ_g36k"
-- L["wep." .. w .. ".name.full"] = "HK HK243"
-- L["wep." .. w .. ".name"] = "HK243"
-- L["wep." .. w .. ".desc"] = "Semi-automatic model of an iconic polymer rifle.\nUses reduced capacity magazines."
-- L["wep." .. w .. ".desc.quote"] = "\"Weapons of war do not belong on our streets!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "civ_m320"
-- L["wep." .. w .. ".name.full"] = "HK M320LE"
-- L["wep." .. w .. ".name"] = "M320LE"
-- L["wep." .. w .. ".desc"] = "Law Enforcement version of the M320 sanctioned for less-lethal munitions. Fires beanbag rounds that incapacitate on direct hit."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "civ_mp5"
-- L["wep." .. w .. ".name.full"] = "HK HK94"
-- L["wep." .. w .. ".name"] = "HK94"
-- L["wep." .. w .. ".desc"] = "Semi-automatic model of a legendary submachine gun. \nUses reduced capacity magazines."
-- L["wep." .. w .. ".desc.quote"] = "Frequently seen standing in for its military counterpart."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention \nModel Edit: speedonerd \n(it was soooo hard lol)"

w = ws .. "civ_p90"
-- L["wep." .. w .. ".name.full"] = "FN PS90"
-- L["wep." .. w .. ".name"] = "PS90"
-- L["wep." .. w .. ".desc"] = "Semi-automatic variation of a futuristic PDW. \nUses reduced capacity magazines."
-- L["wep." .. w .. ".desc.quote"] = "\"This is a weapon of terror. It's made to intimidate the enemy.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention \nModel Edit: speedonerd \n(it was soooo hard lol)"

w = ws .. "dsa58"
-- L["wep." .. w .. ".name.full"] = "DSA SA58 OSW"
-- L["wep." .. w .. ".name"] = "SA58"
-- L["wep." .. w .. ".desc"] = "Battle rifle with slow fire rate but very high damage and armor penetration. Has a grippod that provides some stability if deployed."
-- L["wep." .. w .. ".desc.quote"] = "\"Shut up, clock in and load up.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "DS Arms"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "ex_ak47"
-- L["wep." .. w .. ".name"] = "AK-47"
-- L["wep." .. w .. ".desc"] = "Iconic Soviet assault rifle. A rugged and simple design that inspired countless clones and derivatives."
-- L["wep." .. w .. ".desc.quote"] = "The quintessential bad guy gun."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Kalashnikov Concern"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta, PoisonHeadcrab, Steelbeast \nTextures: Millenia, IppE, FxDarkloki, Pete \nSounds: CC5, modderfreak, .exe \nAnimations: Tactical Intervention"

w = ws .. "ex_glock"
-- L["wep." .. w .. ".name"] = "Glock 17"
-- L["wep." .. w .. ".desc"] = "Polymer pistol with larger-than-standard capacity and a fast fire rate."
-- L["wep." .. w .. ".desc.quote"] = "Does not show up on airport metal detectors."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Glock Ges.m.b.H"
-- L["wep." .. w .. ".credits"] = "Assets: Twinke Masta \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "ex_hecate"
-- L["wep." .. w .. ".name.full"] = "PGM Hécate II"
-- L["wep." .. w .. ".name"] = "Hécate II"
-- L["wep." .. w .. ".desc"] = "Heavy anti-materiel rifle that can kill in one shot. \nEquipped with a 12x scope by default. \nLight enough for swing for melee."
-- L["wep." .. w .. ".desc.quote"] = "Gun Runner tested, NCR approved."
-- L["wep." .. w .. ".trivia.manufacturer"] = "PGM Précision"
-- L["wep." .. w .. ".credits"] = "Assets: Toby Burnside \nSource: Fallout 4: New Vegas Project"

w = ws .. "ex_hk45c"
-- L["wep." .. w .. ".name.full"] = "HK HK45 Compact"
-- L["wep." .. w .. ".name"] = "HK45C"
-- L["wep." .. w .. ".desc"] = "Modern high-caliber pistol with great firepower in a handy package."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: B0t, Red Crayon \nTextures: IppE, Grall19 \nSounds: DMG, xLongWayHome, Leeroy Newman \nAnimations: Tactical Intervention"

w = ws .. "ex_m4a1"
-- L["wep." .. w .. ".name.full"] = "Colt M4A1"
-- L["wep." .. w .. ".name"] = "M4A1"
-- L["wep." .. w .. ".desc"] = "A true American classic boasting high fire rate and balanced performance."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Model/Textures: Twinke Masta, DMG \nSounds: Teh Strelok \nAnimations: Tactical Intervention"

w = ws .. "ex_m1911"
-- L["wep." .. w .. ".name.full"] = "Colt M1911"
-- L["wep." .. w .. ".name"] = "M1911"
-- L["wep." .. w .. ".desc"] = "Surplus pistol from an era before tactical attachments and pistol optics, yet still hits quite hard."
-- L["wep." .. w .. ".desc.quote"] = "\"Hasta la vista, baby!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Model/Textures: Twinke Masta, DMG \nSounds: xLongWayHome, Strelok, Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "ex_mac10"
-- L["wep." .. w .. ".name.full"] = "Ingram MAC-11"
-- L["wep." .. w .. ".name"] = "MAC-11"
-- L["wep." .. w .. ".desc"] = "A bullet hose best used for point blank spray-and-pray."
-- L["wep." .. w .. ".desc.quote"] = "\"Give me the motherfuckin' gun, Tre!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Military Armament Corporation"
-- L["wep." .. w .. ".credits"] = "Model/Textures: Enron \nSounds: Vunsunta,  Erick F \nAnimations: Tactical Intervention"

w = ws .. "ex_mp9"
-- L["wep." .. w .. ".name.full"] = "BT MP9"
-- L["wep." .. w .. ".name"] = "MP9"
-- L["wep." .. w .. ".desc"] = "Compact polymer submachine gun packing lots of firepower in a small package."
-- L["wep." .. w .. ".desc.quote"] = "\"Your right hand comes off?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Brügger & Thomet"
-- L["wep." .. w .. ".credits"] = "Assets: Logger & The Expert \nSource: Gamebanana"

w = ws .. "ex_stinger"
-- L["wep." .. w .. ".name.full"] = "FIM-92 Stinger"
-- L["wep." .. w .. ".name"] = "Stinger"
-- L["wep." .. w .. ".desc"] = "Homing anti-air missile launcher. High blast damage but limited effect on armored targets. \nRequires a lock-on in order to fire."
-- L["wep." .. w .. ".desc.quote"] = "\"A cornered fox is more dangerous than a jackal!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Raytheon Missiles and Defense"
-- L["wep." .. w .. ".credits"] = "Assets: Modern Warfare 2 \nAnimations: Tactical Intervention"

w = ws .. "ex_ump45"
-- L["wep." .. w .. ".name.full"] = "HK UMP45"
-- L["wep." .. w .. ".name"] = "UMP45"
-- L["wep." .. w .. ".desc"] = "Boxy SMG developed with low production costs in mind. \nHigh damage up close, but range and rate of fire is low."
-- L["wep." .. w .. ".desc.quote"] = "\"The fuck are these, cocktail guns?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Hellspike, Logger & Cyper \nSource: Gamebanana"

w = ws .. "ex_usp"
-- L["wep." .. w .. ".name.full"] = "HK USP"
-- L["wep." .. w .. ".name"] = "USP"
-- L["wep." .. w .. ".desc"] = "Tactical pistol with good damage and range."
-- L["wep." .. w .. ".desc.quote"] = "\"Man of few words, aren't you?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: Thanez, Racer445 \nTextures: Thanez, fxdarkloki \nSounds: Vunsunta, BlitzBoaR \nAnimations: Tactical Intervention"

w = ws .. "fp6"
-- L["wep." .. w .. ".name.full"] = "HK FABARM FP6"
-- L["wep." .. w .. ".name"] = "FABARM FP6"
-- L["wep." .. w .. ".desc"] = "Combat shotgun with high fire rate and capacity."
-- L["wep." .. w .. ".trivia.manufacturer"] = "FABARM S.p.A."
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "g36k"
-- L["wep." .. w .. ".name.full"] = "HK G36K"
-- L["wep." .. w .. ".name"] = "G36K"
-- L["wep." .. w .. ".desc"] = "Assault rifle with high muzzle velocity. Well suited for medium range sustained fire. \nEquipped with a 2x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "gsr1911"
-- L["wep." .. w .. ".name.full"] = "SIG 1911 TACOPS"
-- L["wep." .. w .. ".name"] = "SIG 1911"
-- L["wep." .. w .. ".desc"] = "High damage pistol with low range and capacity. \nA tactical evolution, or some would call devolution, of a venerable classic."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer, Inc."
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "hk417"
-- L["wep." .. w .. ".name.full"] = "HK HK417"
-- L["wep." .. w .. ".name"] = "HK417"
-- L["wep." .. w .. ".desc"] = "Battle rifle with superb damage, fire rate and precision. Capable of automatic fire, although it is very unstable."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "k1a"
-- L["wep." .. w .. ".name.full"] = "Daewoo K1A"
-- L["wep." .. w .. ".name"] = "K1A"
-- L["wep." .. w .. ".desc"] = "Burst rifle with minimal recoil and good hip firing accuracy."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Daewoo Precision"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "knife"
-- L["wep." .. w .. ".name"] = "Flip Knife"
-- L["wep." .. w .. ".desc"] = "A multi-purpose flip knife, although most of the purposes involving stabbing someone."
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "knife2"
-- L["wep." .. w .. ".name"] = "Jackal Knife"
-- L["wep." .. w .. ".desc"] = "Very edgy looking knife. Light, partially skeletized blade makes it faster to swing but do less damage."
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention (Unused)"

w = ws .. "ks23"
-- L["wep." .. w .. ".name"] = "KS-23"
-- L["wep." .. w .. ".desc"] = "Made from recycled aircraft gun barrels, this heavy shotgun fires shells with twice the diameter of typical shotshells and can easily tear apart anything it's vaguely pointed at. Able to breach doors."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
-- L["wep." .. w .. ".credits"] = "Assets: Firearms: Source"

w = ws .. "m1"
-- L["wep." .. w .. ".name.full"] = "Ruger Mini-14"
-- L["wep." .. w .. ".name"] = "Mini-14"
-- L["wep." .. w .. ".desc"] = "Lightweight rifle with no stock or optic mount. \nGood hip-fire accuracy among rifles, but range is low."
-- L["wep." .. w .. ".desc.quote"] = "\"The one with the gun gets to tell the truth.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Sturm, Ruger & Co."
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "m4"
-- L["wep." .. w .. ".name.full"] = "Diemaco C8A1"
-- L["wep." .. w .. ".name"] = "C8A1"
-- L["wep." .. w .. ".desc"] = "A close cousin to the classic American rifle with a slower but more controllable rate of fire."
-- L["wep." .. w .. ".desc.quote"] = "Green and very, very mean."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt Canada"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "m4star10"
-- L["wep." .. w .. ".name.full"] = "Benelli M4 Super 90"
-- L["wep." .. w .. ".name"] = "M4 Super 90"
-- L["wep." .. w .. ".desc"] = "Semi-automatic shotgun with very high damage output. Reloading may be a chore."
-- L["wep." .. w .. ".desc.quote"] = "There's nothing seven 12 Gauge shotshells can't solve."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Benelli Armi S.p.A."
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "m14"
-- L["wep." .. w .. ".name.full"] = "Springfield M1A"
-- L["wep." .. w .. ".name"] = "M1A"
-- L["wep." .. w .. ".desc"] = "Semi-automatic rifle with a lethal headshot. \nEquipped with a 6x scope by default."
-- L["wep." .. w .. ".desc.quote"] = "\"This my rifle! There are many like it, but this one is mine!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Springfield Armory"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "m320"
-- L["wep." .. w .. ".name.full"] = "HK M320"
-- L["wep." .. w .. ".name"] = "M320"
-- L["wep." .. w .. ".desc"] = "Grenade launcher capable of firing a variety of payloads."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "medkit"
L["wep." .. w .. ".name"] = "急救包"
L["wep." .. w .. ".desc"] = "装满医疗补给的小包，治疗伤口用。"
-- L["wep." .. w .. ".desc.quote"] = "\"Keep still, let me patch you up.\""
-- L["wep." .. w .. ".credits"] = "Model/Textures: Left 4 Dead 2 \nAnimations: Arqu"

w = ws .. "mg4"
-- L["wep." .. w .. ".name.full"] = "HK MG4"
-- L["wep." .. w .. ".name"] = "MG4"
-- L["wep." .. w .. ".desc"] = "Machine gun with huge volume of fire."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "mp5"
-- L["wep." .. w .. ".name.full"] = "HK MP5A3"
-- L["wep." .. w .. ".name"] = "MP5A3"
-- L["wep." .. w .. ".desc"] = "Well-balanced submachine gun known for its precision."
-- L["wep." .. w .. ".desc.quote"] = "\"Now I have a machine gun. Ho, ho, ho.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "mp7"
-- L["wep." .. w .. ".name.full"] = "HK MP7"
-- L["wep." .. w .. ".name"] = "MP7"
-- L["wep." .. w .. ".desc"] = "PDW with superb handling and close range effectiveness. High velocity rounds retain effectiveness at range and pierces armor easily."
-- L["wep." .. w .. ".desc.quote"] = "\"You forgot to cock it, muthafucka!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "mr96"
-- L["wep." .. w .. ".name.full"] = "Manurhin MR96"
-- L["wep." .. w .. ".name"] = "MR96"
-- L["wep." .. w .. ".desc"] = "Magnum revolver with good handling and stopping power. Accurate, but hard to fire rapidly."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Chapuis Armes"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "mtx_dual"
-- L["wep." .. w .. ".name"] = "Dual MTX"
-- L["wep." .. w .. ".desc"] = "An indulgent pair of high capacity, high damage, high quality compact pistols."
-- L["wep." .. w .. ".desc.quote"] = "With firepower like this, who needs aiming?"
-- L["wep." .. w .. ".trivia.manufacturer"] = "Detonics Defense"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "nade_charge"
-- L["wep." .. w .. ".name.full"] = "Breaching Charge"

w = ws .. "nade_flashbang"
-- L["wep." .. w .. ".name.full"] = "Flashbang"

w = ws .. "nade_frag"
-- L["wep." .. w .. ".name.full"] = "Frag Grenade"

w = ws .. "nade_gas"
-- L["wep." .. w .. ".name.full"] = "CS Gas Grenade"

w = ws .. "nade_heal"
-- L["wep." .. w .. ".name.full"] = "Medi-Smoke Canister"

w = ws .. "nade_smoke"
-- L["wep." .. w .. ".name.full"] = "Smoke Grenade"

w = ws .. "nade_thermite"
-- L["wep." .. w .. ".name"] = "Thermite Grenade"

w = ws .. "p90"
-- L["wep." .. w .. ".name.full"] = "FN P90"
-- L["wep." .. w .. ".name"] = "P90"
-- L["wep." .. w .. ".desc"] = "Bullpup PDW with a generous top-loaded magazine and controllable spread. High velocity rounds retain effectiveness at range and pierces armor easily."
-- L["wep." .. w .. ".desc.quote"] = "\"This is a weapon of war, it's made to kill your enemy.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "p250"
-- L["wep." .. w .. ".name.full"] = "SIG P250"
-- L["wep." .. w .. ".name"] = "P250"
-- L["wep." .. w .. ".desc"] = "Powerful handgun that exchanges capacity for damage and precision."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer, Inc."
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "p2000"
-- L["wep." .. w .. ".name.full"] = "HK P2000"
-- L["wep." .. w .. ".name"] = "P2000"
-- L["wep." .. w .. ".desc"] = "Well-rounded, run-of-the-mill police handgun."
-- L["wep." .. w .. ".desc.quote"] = "\"Raus! Raus! Raus!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "pdw"
-- L["wep." .. w .. ".name"] = "KAC PDW"
-- L["wep." .. w .. ".desc"] = "Carbine caliber subcompact PDW. The perfect blend of rifle and submachine gun."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Knight's Armament"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "riot_shield"
L["wep." .. w .. ".name"] = "防暴盾"
L["wep." .. w .. ".desc"] = "轻型护盾。 \n虽然看上去是塑料的，但能格挡大部分步枪口径子弹。 \n能冲刺时攻击且不暴露自己，但会稍微降低移动速度。"
-- L["wep." .. w .. ".credits"] = "Model/Textures: Tactical Intervention \nAnimations: Arqu"

w = ws .. "rpg7"
-- L["wep." .. w .. ".name"] = "RPG-7"
-- L["wep." .. w .. ".desc"] = "Soviet rocket launcher with powerful explosion. \nSafety fuse prevents point blank detonations."
-- L["wep." .. w .. ".desc.quote"] = "If you hear someone screaming its name, duck for cover."
-- L["wep." .. w .. ".trivia.manufacturer"] = "NPO Bazalt"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "sg551"
-- L["wep." .. w .. ".name.full"] = "SIG SG 551"
-- L["wep." .. w .. ".name"] = "SG 551"
-- L["wep." .. w .. ".desc"] = "Assault rifle with all around excellent performance, offset by a lower magazine capacity."
-- L["wep." .. w .. ".desc.quote"] = "\"No questions, no answers. That's the business we're in.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "skorpion"
-- L["wep." .. w .. ".name.full"] = "Skorpion vz. 61"
-- L["wep." .. w .. ".name"] = "Skorpion"
-- L["wep." .. w .. ".desc"] = "Light machine pistol with good range, recoil and spread."
-- L["wep." .. w .. ".trivia.manufacturer"] = "CZ Uherský Brod"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "sphinx"
-- L["wep." .. w .. ".name.full"] = "Sphinx 2000"
-- L["wep." .. w .. ".name"] = "Sphinx"
-- L["wep." .. w .. ".desc"] = "Premium pistol modified to be 3-round burst. High firerate but long burst delay."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Sphinx Systems"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "spr"
-- L["wep." .. w .. ".name.full"] = "Remington M700 SPS"
-- L["wep." .. w .. ".name"] = "R700 SPS"
-- L["wep." .. w .. ".desc"] = "Medium range hunting rifle with a fast cycle speed. \nEquipped with a 6x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Remington Arms"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "superv"
-- L["wep." .. w .. ".name.full"] = "Kriss Vector"
-- L["wep." .. w .. ".name"] = "Vector"
-- L["wep." .. w .. ".desc"] = "Close range SMG with extremely high fire rate and practically no recoil. Low armor penetration, but can chew through it very quickly."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Kriss USA, Inc."
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "tgs12"
-- L["wep." .. w .. ".name.full"] = "Tomahawk Matador"
-- L["wep." .. w .. ".name"] = "Matador"
-- L["wep." .. w .. ".desc"] = "Short barrel pistol grip shotgun. High mobility and recoil, and most effective at close range."
-- L["wep." .. w .. ".desc.quote"] = "For years, its true identity was a mystery."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tomahawk Shotguns"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "uratio"
-- L["wep." .. w .. ".name.full"] = "PGM Ultima Ratio"
-- L["wep." .. w .. ".name"] = "Ultima Ratio"
-- L["wep." .. w .. ".desc"] = "Lightweight sniper rifle with good damage and high mobility. \nEquipped with a 10x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "PGM Précision"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "uzi"
-- L["wep." .. w .. ".name.full"] = "IMI Uzi Pro"
-- L["wep." .. w .. ".name"] = "Uzi Pro"
-- L["wep." .. w .. ".desc"] = "Balanced machine pistol with a controllable rate of fire."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Israel Military Industries"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "vertec"
-- L["wep." .. w .. ".name.full"] = "Beretta 92FS Vertec"
-- L["wep." .. w .. ".name"] = "92FS Vertec"
L["wep." .. w .. ".desc"] = "意大利产手枪。射程和命中率较高。"
-- L["wep." .. w .. ".desc.quote"] = "\"Yippie ki-yay, motherfucker!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "xd45"
-- L["wep." .. w .. ".name.full"] = "Springfield XD-45"
-- L["wep." .. w .. ".name"] = "XD-45"
-- L["wep." .. w .. ".desc"] = "Automatic machine pistol with incredible close range power."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Springfield Armory"
-- L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

-- Attachments (Non-Bulk)
L["att.melee_spec_charge.name.full"] = "demoknight tf2"
L["att.melee_spec_charge.name"] = "Charge"
L["att.melee_spec_charge.desc"] = "Advance with reckless abandon, and break some laws of physics too."
L["att.pro.melee_spec_charge1"] = "RELOAD: Charge"
L["att.pro.melee_spec_charge2"] = "WALK + RELOAD: Select Charge Mode"
L["att.pro.melee_spec_charge3"] = "Reduced Damage while Charging"
L["att.pro.melee_spec_charge4"] = "Reduced Self-Damage"

L["att.melee_spec_lunge.name"] = "Frency"
L["att.melee_spec_lunge.desc"] = "Close the distance and overwhelm your enemies."
L["att.pro.melee_spec_lunge1"] = "RELOAD: Lunge in Aim Direction"

L["att.melee_spec_nade.name.full"] = "Bombardier"
L["att.melee_spec_nade.name"] = "Bomber"
L["att.melee_spec_nade.desc"] = "Use jury-rigged impact grenades to ruin someone's day."
L["att.pro.melee_spec_nade1"] = "RELOAD: Toggle Grenades"
L["att.pro.melee_spec_nade2"] = "Grenades Explode on Impact"
L["att.con.melee_spec_nade"] = "Grenade Damage"

L["att.melee_spec_ninja.name"] = "Ninja"
L["att.melee_spec_ninja.desc"] = "Disrupt your enemies and strike with the element of surprise."
L["att.pro.melee_spec_ninja1"] = "RELOAD: Palm Strike / Climb"
L["att.pro.melee_spec_ninja2"] = "RELOAD: (Mid-Air + Crouch): Dive Kick"
L["att.pro.melee_spec_ninja3"] = "RELOAD: (Crouch): Backhop"
L["att.pro.melee_spec_ninja4"] = "Silent Footsteps"

L["att.melee_spec_scout.name.full"] = "jerma tf2"
L["att.melee_spec_scout.name"] = "Scout"
L["att.melee_spec_scout.desc"] = "Grass grows, sun shines, birds fly, and brotha' - I hurt people."
L["att.pro.melee_spec_scout1"] = "RELOAD: Launch Ball"
L["att.pro.melee_spec_scout2"] = "Ball Damage Scales with Distance"
L["att.pro.melee_spec_scout3"] = "Ball Applies Slow on Hit"
L["att.pro.melee_spec_scout4"] = "Multi Jump"

L["att.melee_spec_step.name"] = "Airdash"
L["att.melee_spec_step.desc"] = "Mobility tool used by blood-fueled robots and transgender women."
L["att.pro.melee_spec_step1"] = "RELOAD: Dash in Movement Direction"
L["att.pro.melee_spec_step2"] = "Invulnerable while Dashing"

L["att.melee_spec_block.name.full"] = "High Guard"
L["att.melee_spec_block.name"] = "Guard"
L["att.melee_spec_block.desc"] = "Defense is the best offense. It is, coincidentally, also the best defense."
L["att.pro.melee_spec_block1"] = "ALT-FIRE: Block Melee Attacks or Projectiles"
L["att.pro.melee_spec_block2"] = "Heavy Counterattack After Successful Block"

L["att.melee_spec_heavy.name.full"] = "Heavy-handed"
L["att.melee_spec_heavy.name"] = "Heavy"
L["att.melee_spec_heavy.desc"] = "A classic counter-terrorist technique: Just smack them real hard."
L["att.pro.melee_spec_heavy1"] = "ALT-FIRE: Heavy Attack"
L["att.pro.melee_spec_heavy2"] = "Backstab Damage"

L["att.melee_tech_nade.name.full"] = "Grenadier"
L["att.melee_tech_nade.name"] = "Grenade"
L["att.melee_tech_nade.desc"] = "Always good to have something handy to throw."
L["att.pro.melee_tech_nade1"] = "ALT-FIRE: Quickthrow"
L["att.pro.melee_tech_nade2"] = "Faster Quickthrow"
L["att.pro.melee_tech_nade3"] = "Throw Rocks"

L["att.melee_tech_throw.name.full"] = "Knife Throw"
L["att.melee_tech_throw.name"] = "Throw"
L["att.melee_tech_throw.desc"] = "Bar trick turned lethal."
L["att.pro.melee_tech_throw1"] = "ALT-FIRE: Throw Weapon"
L["att.pro.melee_tech_throw2"] = "Consumes Crossbow Bolt Ammo"
L["att.pro.melee_tech_throw3"] = "Bonus Headshot Damage"
L["att.pro.melee_tech_throw4"] = "Bonus Damage on Slowed/Stunned Targets"

-- Attachments (acc)
L["att.acc_bipod.name"] = "两脚架"
L["att.acc_bipod.desc"] = "可折叠的架子，蹲下使用可以稳定武器。"

L["att.acc_brace.name"] = "手枪后托"
L["att.acc_brace.desc"] = "架在肩膀上提升手枪稳定性。"

L["att.acc_cheekrest.name"] = "枪托枕"
L["att.acc_cheekrest.desc"] = "枕住下巴，降低瞄准时的武器摇晃。"

L["att.acc_dual_ergo.name.full"] = "人体学握把"
L["att.acc_dual_ergo.name"] = "人体学握把"
L["att.acc_dual_ergo.desc"] = "更顺手的后握把，开火时移速增加。"

L["att.acc_dual_quickdraw.name.full"] = "快切皮套"
L["att.acc_dual_quickdraw.name"] = "快切皮套"
L["att.acc_dual_quickdraw.desc"] = "没有扣子的皮套，可提升切换和装填速度。"

L["att.acc_dual_skel.name.full"] = "骨架化握把"
L["att.acc_dual_skel.name"] = "骨架化握把"
L["att.acc_dual_skel.desc"] = "更轻盈的后握把，提升移动速度。"

L["att.acc_duffelbag.name"] = "暗兜皮套"
L["att.acc_duffelbag.desc"] = "藏匿收起的武器，让其他人看不到。"

L["att.acc_ergo.desc"] = "更顺手的后握把，开火时移速增加。"

L["att.acc_extendedbelt.name.full"] = "扩容弹盒"
L["att.acc_extendedbelt.name"] = "扩容弹盒"
L["att.acc_extendedbelt.desc"] = "显著提升机枪的弹药装填量。"

L["att.acc_extmag.name.full"] = "扩容弹匣"
L["att.acc_extmag.name"] = "扩容弹匣"
L["att.acc_extmag.desc"] = "小幅提升武器的弹药装填量。"

L["att.acc_foldstock.name"] = "折叠枪托"
L["att.acc_foldstock.desc"] = "不使用枪托。"

L["att.acc_foldstock2.name"] = "收短枪托"
L["att.acc_foldstock2.desc"] = "将枪托变短。"

L["att.acc_pad.name"] = "枪托垫"
L["att.acc_pad.desc"] = "枪托底部插入的橡胶垫子，降低后坐力。"

L["att.acc_quickdraw.desc"] = "没有扣子的皮套，可提升切换和装填速度。"

L["att.acc_skel.desc"] = "更轻盈的后握把，瞄准时移速增加。"

L["att.acc_sling.name"] = "枪带"
L["att.acc_sling.desc"] = "固定在枪上的皮带，可提升切换和装填速度。"

-- Attachments (ammo)
L["att.ammo_40mm_3gl.name.full"] = "40mm 三联弹"
L["att.ammo_40mm_3gl.name"] = "三联弹"
L["att.ammo_40mm_3gl.desc"] = "一次射出三颗伤害较低的弹头。"

L["att.ammo_40mm_buck.name.full"] = "40mm 霰弹"
L["att.ammo_40mm_buck.name"] = "霰弹"
L["att.ammo_40mm_buck.desc"] = "射出高威力弹丸的扁平弹头。"

L["att.ammo_40mm_gas.name.full"] = "40mm 催泪弹"
L["att.ammo_40mm_gas.name"] = "催泪弹"
L["att.ammo_40mm_gas.desc"] = "产生非致命催泪气体的弹头。"

L["att.ammo_40mm_heat.name.full"] = "40mm 箭弹"
L["att.ammo_40mm_heat.name"] = "箭弹"
L["att.ammo_40mm_heat.desc"] = "射出高精度铁箭的扁平弹头。"

L["att.ammo_40mm_lvg.name.full"] = "40mm 震撼弹"
L["att.ammo_40mm_lvg.name"] = "震撼弹"
L["att.ammo_40mm_lvg.desc"] = "射出有闪光效果的弹头。弹头落地后会延迟引爆。"

L["att.ammo_40mm_ratshot.name.full"] = "40mm 空爆弹"
L["att.ammo_40mm_ratshot.name"] = "空爆弹"
L["att.ammo_40mm_ratshot.desc"] = "延时空爆的弹头，杀伤范围很大。"

L["att.ammo_40mm_smoke.name.full"] = "40mm 烟雾弹"
L["att.ammo_40mm_smoke.name"] = "烟雾弹"
L["att.ammo_40mm_smoke.desc"] = "射出无伤害的烟雾，可以隐蔽自己。"

L["att.ammo_40mm_heal.name.full"] = "40mm 治疗弹"
L["att.ammo_40mm_heal.name"] = "治疗弹"
L["att.ammo_40mm_heal.desc"] = "射出有治疗效果的烟雾。"

L["att.ammo_amr_hv.name.full"] = "高速狙击弹"
L["att.ammo_amr_hv.name"] = "高速狙击弹"
L["att.ammo_amr_hv.desc"] = "高射程高速度的弹药，近距离杀伤效果变弱。"

L["att.ammo_amr_ratshot.name.full"] = "猎鼠狙击弹"
L["att.ammo_amr_ratshot.name"] = "猎鼠狙击弹"
L["att.ammo_amr_ratshot.desc"] = "装有微小弹丸的大口径弹药，更容易命中目标。"

L["att.ammo_amr_saphe.name.full"] = "高爆狙击弹"
L["att.ammo_amr_saphe.name"] = "高爆狙击弹"
L["att.ammo_amr_saphe.desc"] = "产生爆炸效果的大口径弹药。"

L["att.ammo_ks23_flashbang.name.full"] = "Zvezda 闪光弹"
L["att.ammo_ks23_flashbang.name"] = "闪光弹"
L["att.ammo_ks23_flashbang.desc"] = "可造成小范围眩晕的特种弹药，射程很短且无伤害。"

L["att.ammo_ks23_flashbang_top.name.full"] = "Zvezda 闪光弹（首发）"
L["att.ammo_ks23_flashbang_top.name"] = "闪光弹（首发）"
L["att.ammo_ks23_flashbang_top.desc"] = "第一发装填闪光弹，后续弹药可正常使用。"

L["att.ammo_magnum.name.full"] = "过压弹"
L["att.ammo_magnum.name"] = "过压弹"
L["att.ammo_magnum.desc"] = "过量火药能更好维持近距离杀伤力，但更难控制。"

L["att.ammo_pistol_ap.name.full"] = "钢头弹"
L["att.ammo_pistol_ap.name"] = "钢头弹"
L["att.ammo_pistol_ap.desc"] = "硬化弹头提升穿透效果，但杀伤效果变弱。"

L["att.ammo_pistol_headshot.name.full"] = "猎头弹"
L["att.ammo_pistol_headshot.name"] = "猎头弹"
L["att.ammo_pistol_headshot.desc"] = "对人型目标弱点效果更好的弹药。"

L["att.ammo_pistol_hollowpoints.name.full"] = "空尖弹"
L["att.ammo_pistol_hollowpoints.name"] = "空尖弹"
L["att.ammo_pistol_hollowpoints.desc"] = "对肉体杀伤力效果更好的弹药。"

L["att.ammo_rifle_jhp.name.full"] = "披甲空尖弹"
L["att.ammo_rifle_jhp.name"] = "披甲空尖弹"
L["att.ammo_rifle_jhp.desc"] = "对肉体和臂膀杀伤力更好的弹药。"

L["att.ammo_pistol_match.name.full"] = "手枪竞赛弹"
L["att.ammo_pistol_match.name"] = "竞赛弹"
L["att.ammo_pistol_match.desc"] = "提升精准度和射程的弹药。"

L["att.ammo_rifle_match.name.full"] = "步枪竞赛弹"
L["att.ammo_rifle_match.name"] = "竞赛弹"
L["att.ammo_rifle_match.desc"] = "精准度很高的弹药。"

L["att.ammo_roulette.name.full"] = "俄罗斯轮盘"
L["att.ammo_roulette.name"] = "俄罗斯轮盘"
L["att.ammo_roulette.desc"] = "拿你的性命下注。有子弹时装填可重置概率。"

L["att.ammo_rpg_improvised.name.full"] = "RPG-7 土制火箭"
L["att.ammo_rpg_improvised.name"] = "土制"
L["att.ammo_rpg_improvised.desc"] = "低价拼单抢来的，应该不会出事吧。"

L["att.ammo_rpg_mortar.name.full"] = "RPG-7 迫击炮火箭"
L["att.ammo_rpg_mortar.name"] = "迫击炮"
L["att.ammo_rpg_mortar.desc"] = "给迫击炮上装了推进器，用来\"间接\"打击。需要一定时间起爆。"

L["att.ammo_rpg_ratshot.name.full"] = "RPG-7 空爆火箭"
L["att.ammo_rpg_ratshot.name"] = "空爆"
L["att.ammo_rpg_ratshot.desc"] = "延时空爆的火箭，杀伤范围极高。"

L["att.ammo_rpg_harpoon.name.full"] = "RPG-7 铲子火箭"
L["att.ammo_rpg_harpoon.name"] = "铲子"
L["att.ammo_rpg_harpoon.desc"] = "以神秘的方式发射铲子。你是疯了，火箭用完了，还是两个都有？"

L["att.ammo_shotgun_bird.name"] = "鸟弹"
L["att.ammo_shotgun_bird.desc"] = "高弹丸量高散射的弹药。"

L["att.ammo_shotgun_mag.name.full"] = "马格南鹿弹"
L["att.ammo_shotgun_mag.name"] = "马格南鹿弹"
L["att.ammo_shotgun_mag.desc"] = "能更好维持近距离杀伤力的弹药。"

L["att.ammo_shotgun_slugs.name.full"] = "独头弹"
L["att.ammo_shotgun_slugs.name"] = "独头弹"
L["att.ammo_shotgun_slugs.desc"] = "发射单颗弹丸，显著提高准度和射程。"

L["att.ammo_shotgun_triple.name.full"] = "三击弹"
L["att.ammo_shotgun_triple.name"] = "三击弹"
L["att.ammo_shotgun_triple.desc"] = "发射三颗中型弹丸，提高准度。"

L["att.ammo_subsonic.name.full"] = "亚音弹"
L["att.ammo_subsonic.name"] = "亚音弹"
L["att.ammo_subsonic.desc"] = "通过减少火药降低子弹速度，可隐藏弹道并降低后坐力。"

L["att.ammo_surplus.name.full"] = "次品弹"
L["att.ammo_surplus.name"] = "次品弹"
L["att.ammo_surplus.desc"] = "不太靠谱的弹药，但不知为何满地都是。"

L["att.ammo_tmj.name.full"] = "披甲弹"
L["att.ammo_tmj.name"] = "披甲弹"
L["att.ammo_tmj.desc"] = "提升穿透力的弹药。"

L["att.ammo_buckshot_roulette.name.full"] = "霰弹轮盘赌"
L["att.ammo_buckshot_roulette.name"] = "霰弹轮盘赌"
L["att.ammo_buckshot_roulette.desc"] = "子弹以未知顺序进入枪膛。"

L["att.ammo_shotgun_minishell.name.full"] = "迷你弹"
L["att.ammo_shotgun_minishell.name"] = "迷你弹"
L["att.ammo_shotgun_minishell.desc"] = "长度很短的霰弹弹药，增加装填量但降低弹丸量。"

L["att.ammo_shotgun_dragon.name.full"] = "龙息弹"
L["att.ammo_shotgun_dragon.name"] = "龙息弹"
L["att.ammo_shotgun_dragon.desc"] = "镁制弹头能点然目标，但伤害和射程都较低。"

L["att.ammo_shotgun_frag.name.full"] = "高爆破片弹"
L["att.ammo_shotgun_frag.name"] = "破片弹"
L["att.ammo_shotgun_frag.desc"] = "能造成范围伤害的弹药，但伤害很低。"

L["att.ammo_shotgun_breach.name.full"] = "破门弹（首发）"
L["att.ammo_shotgun_breach.name"] = "破门弹"
L["att.ammo_shotgun_breach.desc"] = "第一发装填能够破门的特种弹头。"

-- L["att.ammo_stinger_saam.name.full"] = "FIM-92 Stinger Semi-Active Missile"
-- L["att.ammo_stinger_saam.name"] = "Semi-Active"
-- L["att.ammo_stinger_saam.desc"] = "Powerful missiles that lock rapidly but require constant guidance."

-- L["att.ammo_stinger_qaam.name.full"] = "FIM-92 Stinger High Agility Missile"
-- L["att.ammo_stinger_qaam.name"] = "Agile"
-- L["att.ammo_stinger_qaam.desc"] = "Highly maneuverable missile with a short range and long lock time."

-- L["att.ammo_stinger_4aam.name.full"] = "FIM-92 Stinger Quad Missiles"
-- L["att.ammo_stinger_4aam.name"] = "4x"
-- L["att.ammo_stinger_4aam.desc"] = "Guided cluster missiles maximize pressure to enemy pilots."

-- L["att.ammo_stinger_apers.name.full"] = "FIM-92 Stinger Anti-Personnel Missiles"
-- L["att.ammo_stinger_apers.name"] = "Killer Bee"
-- L["att.ammo_stinger_apers.desc"] = "For rodents of unacceptable agility."

L["att.ammo_usp_9mm.name.full"] = "HK USP 9×19mm 改装"
L["att.ammo_usp_9mm.name"] = "9×19mm"
L["att.ammo_usp_9mm.desc"] = "发射小口径弹药，提升射速和装填量。"

-- Attachments (bolt_trigger)
L["att.bolt_fine.name.full"] = "精密枪栓"
L["att.bolt_fine.name"] = "精致"
L["att.bolt_fine.desc"] = "后坐力恢复速度变快，但增长速度也更快。"

L["att.bolt_greased.name.full"] = "注油枪栓"
L["att.bolt_greased.name"] = "注油"
L["att.bolt_greased.desc"] = "加快上膛速度，但对枪械性能有影响。"

L["att.bolt_heavy.name.full"] = "稳重枪栓"
L["att.bolt_heavy.name"] = "稳重"
L["att.bolt_heavy.desc"] = "降低后坐力，但也降低射速。"

L["att.bolt_light.name.full"] = "轻盈枪栓"
L["att.bolt_light.name"] = "轻盈"
L["att.bolt_light.desc"] = "加快射速，但提高后坐力。"

L["att.bolt_rough.name.full"] = "耐久枪栓"
L["att.bolt_rough.name"] = "耐久"
L["att.bolt_rough.desc"] = "后坐力增长速度变慢，但恢复速度也变慢。"

L["att.bolt_surplus.name.full"] = "锈铁枪栓"
L["att.bolt_surplus.name"] = "锈铁"
L["att.bolt_surplus.desc"] = "难以捉摸的破旧枪栓，时快时慢。"

L["att.bolt_tactical.name.full"] = "战术枪栓"
L["att.bolt_tactical.name"] = "战术"
L["att.bolt_tactical.desc"] = "控制上膛速度，提升枪械性能。"

L["att.bolt_refurbished.name.full"] = "修缮枪栓"
L["att.bolt_refurbished.name"] = "修缮"
L["att.bolt_refurbished.desc"] = "牺牲一些武器性能以提升可靠性。"

L["att.trigger_akimbo.name.full"] = "双持扳机"
L["att.trigger_akimbo.name"] = "双持"
L["att.trigger_akimbo.desc"] = "放马过来！"

L["att.trigger_burst.name.full"] = "三连发扳机"
L["att.trigger_burst.name"] = "三连发"
L["att.trigger_burst.desc"] = "使用点射模式提高稳定性的扳机，牺牲全自动射击功能。"

L["att.trigger_burst2.desc"] = "模拟连发射击的扳机。"

L["att.trigger_burstauto.name.full"] = "自动点射扳机"
L["att.trigger_burstauto.name"] = "自动点射"
L["att.trigger_burstauto.desc"] = "按住扳机可以让点射不间断开火的扳机。"

L["att.trigger_comp.name.full"] = "竞赛扳机"
L["att.trigger_comp.name"] = "竞赛"
L["att.trigger_comp.desc"] = "用于运动射击的轻质扳机。"

L["att.trigger_comp2.desc"] = "轻质扳机，能更快恢复精准度。"

L["att.trigger_frcd.name.full"] = "强制复位扳机"
L["att.trigger_frcd.name"] = "强制复位"
L["att.trigger_frcd.desc"] = "模拟自动射击的扳机，但性能不佳。"

L["att.trigger_hair.name.full"] = "快速扳机"
L["att.trigger_hair.name"] = "快速"
L["att.trigger_hair.desc"] = "非常灵敏的扳机，可快速半自动射击。"

L["att.trigger_hair_akimbo.desc"] = "非常灵敏的扳机，可让双枪快速开火。"

L["att.trigger_heavy.name.full"] = "重型扳机"
L["att.trigger_heavy.name"] = "重型"
L["att.trigger_heavy.desc"] = "用于持续射击的重型扳机。"

L["att.trigger_heavy2.desc"] = "沉重的扳机，减少了射击时的移速影响。"

L["att.trigger_semi.name.full"] = "射手扳机"
L["att.trigger_semi.name"] = "射手"
L["att.trigger_semi.desc"] = "提高稳定性但牺牲了全自动射击。"

L["att.trigger_slam.name.full"] = "惯性自动扳机"
L["att.trigger_slam.name"] = "惯性"

L["att.trigger_straight.name.full"] = "平移扳机"
L["att.trigger_straight.name"] = "平移"
L["att.trigger_straight.desc"] = "狭窄的扳机，具有卓越的后坐力性能。"

L["att.trigger_wide.name.full"] = "宽幅扳机"
L["att.trigger_wide.name"] = "宽幅"
L["att.trigger_wide.desc"] = "大型扳机组件，即使在尴尬的位置也容易握住。"

L["att.trigger_dualstage.name.full"] = "二阶扳机"
L["att.trigger_dualstage.name"] = "二阶"
L["att.trigger_dualstage.desc"] = "瞄准时降低射速并提升武器可控性的班级。"

-- Attachments (melee_boost)
-- L["att.melee_boost_all.name"] = "Level Up"
-- L["att.melee_boost_all.desc"] = "Small boost to all attributes."

-- L["att.melee_boost_str.name"] = "Bulk Up"
-- L["att.melee_boost_str.desc"] = "Increase Brawn significantly at the cost of other attributes."

-- L["att.melee_boost_agi.name"] = "Catch Up"
-- L["att.melee_boost_agi.desc"] = "Increase Dexterity significantly at the cost of other attributes."

-- L["att.melee_boost_int.name"] = "Wise Up"
-- L["att.melee_boost_int.desc"] = "Increase Strategy significantly at the cost of other attributes."

-- L["att.melee_boost_lifesteal.name"] = "Lifestealer"
-- L["att.melee_boost_lifesteal.desc"] = "Restore health by dealing damage."

-- L["att.melee_boost_momentum.name"] = "Momentum"
-- L["att.melee_boost_momentum.desc"] = "Restore perk charge by dealing damage."

-- L["att.melee_boost_afterimage.name"] = "Afterimage"
-- L["att.melee_boost_afterimage.desc"] = "Swing your weapon in a flash, landing the attack instantly."

L["att.melee_boost_shock.name.full"] = "冲锋队"
L["att.melee_boost_shock.name"] = "冲锋队"
L["att.melee_boost_shock.desc"] = "在持有武器的情况下，减少负面效果的影响。"

-- Attachments (muzz)
L["att.muzz_hbar.name"] = "重枪管"
L["att.muzz_hbar.desc"] = "降低后坐力并提升稳定性的枪管配件。"

L["att.muzz_lbar.name"] = "轻枪管"
L["att.muzz_lbar.desc"] = "提升射程和精准度的枪管配件。"

L["att.muzz_pistol_comp.name"] = "制退器"
L["att.muzz_pistol_comp.desc"] = "显著降低后坐力的枪口配件。"

L["att.muzz_supp_compact.name.full"] = "短型消音器"
L["att.muzz_supp_compact.name"] = "短型消音"
L["att.muzz_supp_compact.desc"] = "提升准度并对射程影响较低的小消音器。"

L["att.muzz_silencer.name.full"] = "战术消音器"
L["att.muzz_silencer.name"] = "战术消音"
L["att.muzz_silencer.desc"] = "降低后坐力和射程的平衡类消音器。"

L["att.muzz_supp_weighted.name.full"] = "加重消音器"
L["att.muzz_supp_weighted.name"] = "加重消音"
L["att.muzz_supp_weighted.desc"] = "提升射程但影响手感的重型消音器。"

L["att.muzz_brake_aggressor.name.full"] = "强袭制退器"
L["att.muzz_brake_aggressor.name"] = "强袭制退"
L["att.muzz_brake_aggressor.desc"] = "转移枪炎方向的制退器，提升射击时移动速度。"

L["att.muzz_brake_breaching.name.full"] = "突破制退器"
L["att.muzz_brake_breaching.name"] = "突破制退"
L["att.muzz_brake_breaching.desc"] = "带刺的制退器，适合近距离作战。"

L["att.muzz_brake_concussive.name.full"] = "寸步制退器"
L["att.muzz_brake_concussive.name"] = "寸步制退"
L["att.muzz_brake_concussive.desc"] = "吵到难受的制退器，大幅降低后坐力。"

-- Attachments (optic_tac)
L["att.optic_8x.name.full"] = "长焦瞄准镜"
L["att.optic_8x.name"] = "长焦"
L["att.optic_8x.desc"] = "专门给狙击手使用的远距离光学镜。"

L["att.optic_acog.name.full"] = "ACOG 瞄准镜"
L["att.optic_acog.name"] = "ACOG"
L["att.optic_acog.desc"] = "中距离战斗准镜。"

L["att.optic_elcan.name.full"] = "ELCAN 瞄准镜"
L["att.optic_elcan.name"] = "ELCAN"
L["att.optic_elcan.desc"] = "低倍率战斗准镜。"

L["att.optic_holographic.name.full"] = "全息瞄准镜"
L["att.optic_holographic.name"] = "全息"
L["att.optic_holographic.desc"] = "盒状准镜，可辅助近距离瞄准。"

L["att.optic_irons.name.full"] = "机械瞄具"
L["att.optic_irons.name"] = "机瞄"
L["att.optic_irons.desc"] = "基础瞄准器，可增加移动性。"

L["att.optic_irons_sniper.desc"] = "替换默认的瞄准镜，获得更快的瞄准和更好的机动性。"

L["att.optic_okp7.name.full"] = "OKP-7 瞄准镜"
L["att.optic_okp7.name"] = "OKP-7"
L["att.optic_okp7.desc"] = "俄罗斯制造的反射式瞄准镜。"

L["att.optic_rds2.name.full"] = "红点瞄准镜"
L["att.optic_rds2.name"] = "红点"
L["att.optic_rds2.desc"] = "视野宽敞的低倍瞄准器。"

L["att.optic_rds.name.full"] = "Aimpoint 瞄准镜"
L["att.optic_rds.name"] = "Aimpoint"
L["att.optic_rds.desc"] = "桶状准镜，可辅助近距离瞄准。"

L["att.optic_rmr.name.full"] = "RMR 瞄准镜"
L["att.optic_rmr.name"] = "RMR"
L["att.optic_rmr.desc"] = "用于手枪的低轮廓光学瞄准器。"

L["att.optic_rmr_rifle.desc"] = "低轮廓光学瞄准器。"

L["att.optic_shortdot.name.full"] = "短点瞄准镜"
L["att.optic_shortdot.name"] = "短点"
L["att.optic_shortdot.desc"] = "紧凑的光学瞄准器，具有不错的缩放率。"

L["att.tac_cornershot.name"] = "拐角摄像机"
L["att.tac_cornershot.desc"] = "在盲射时显示枪口情况。"

L["att.tac_dmic.name"] = "雷达"
L["att.tac_dmic.desc"] = "探测附近目标的位置，但会发出声响。"

L["att.tac_flashlight.name"] = "手电筒"
L["att.tac_flashlight.desc"] = "发出强烈的光束，使盯着它的人致盲。"

L["att.tac_laser.name"] = "镭射"
L["att.tac_laser.desc"] = "发出狭窄的红色光束和圆点，指示枪支的指向。"

L["att.tac_combo.name.full"] = "光瞄组合"
L["att.tac_combo.name"] = "光瞄组合"
L["att.tac_combo.desc"] = "整合手电筒和镭射的二合一配件。手电光太弱，无法干扰他人。"

L["att.tac_rangefinder.name"] = "测距仪"
L["att.tac_rangefinder.desc"] = "衡量武器的弹道性能。"

L["att.tac_spreadgauge.name"] = "扩散测量仪"
L["att.tac_spreadgauge.desc"] = "测量武器的水平后坐力和后坐力的稳定性。"

L["att.tac_magnifier.name"] = "变焦瞄具"
L["att.tac_magnifier.name"] = "变焦瞄具"
L["att.tac_magnifier.desc"] = "让所有瞄具可以切换 2 倍缩放。"

L["att.tac_bullet.name.full"] = "紧急装填"
L["att.tac_bullet.name"] = "紧急装填"
L["att.tac_bullet.desc"] = "较快地装填一颗子弹，以备没时间装填时用。"

L["att.tac_thermal.name.full"] = "热成像"
L["att.tac_thermal.name"] = "热成像"
L["att.tac_thermal.desc"] = "半瞄准时在瞄准中心显示热成像效果。"

-- Attachments (perk)
L["att.perk_aim.name"] = "死神之眼"
L["att.perk_aim.desc"] = "提高瞄准时的枪械性能。"

L["att.perk_blindfire.name.full"] = "掩体射击"
L["att.perk_blindfire.name"] = "掩体射击"
L["att.perk_blindfire.desc"] = "改善盲射和精准腰射。"

L["att.perk_hipfire.name"] = "兰博"
L["att.perk_hipfire.desc"] = "提高不开镜时的枪械精度。"

L["att.perk_melee.name"] = "粉碎"
L["att.perk_melee.desc"] = "提高近战伤害，并使被击中的目标减速。"

L["att.perk_reload.name"] = "快速换弹"
L["att.perk_reload.desc"] = "加快换弹速度。"

L["att.perk_speed.name"] = "身手敏捷"
L["att.perk_speed.desc"] = "提高枪械的机动性，特别是在换弹时。"

L["att.perk_throw.name"] = "掷弹兵"
L["att.perk_throw.desc"] = "加快了快速投掷，并增加了投掷石块的选项。"

-- L["att.perk_mlg.name"] = "Stylish"
-- L["att.perk_mlg.desc"] = "Improves quickscoping and accuracy while jumping or moving."

///////////////////// -- [[ InterOps Weapons ]] --
-- Weapons
ws = "tacrp_io_"
w = ws .. "870"
-- L["wep." .. w .. ".name.full"] = "Remington 870 SPMM"
-- L["wep." .. w .. ".name"] = "R870 SPMM"
-- L["wep." .. w .. ".desc"] = "Nickel plated \"Marine Magnum\" shotgun. Poor handling, but has great capacity and firepower."
-- L["wep." .. w .. ".desc.quote"] = "\"THERE'S GOLD IN THEM THAR HILLS!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Remington"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Millenia \nSounds: Vunsunta, xLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "ab10"
-- L["wep." .. w .. ".name.full"] = "Intratec AB-10"
-- L["wep." .. w .. ".name"] = "AB-10"
-- L["wep." .. w .. ".desc"] = "Semi-automatic \"After Ban\" model of the TEC-9 with a short, non-threaded barrel. Big magazine, but unreliable."
-- L["wep." .. w .. ".desc.quote"] = "\"Who needs an assault weapon?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Intratec"
-- L["wep." .. w .. ".credits"] = "Model/Textures: Payday 2 \nSounds: The_AntiPirate \nAnimations: Tactical Intervention"

w = ws .. "af2011"
-- L["wep." .. w .. ".name.full"] = "AF2011-A1"
-- L["wep." .. w .. ".name"] = "AF2011"
-- L["wep." .. w .. ".desc"] = "Effectively two M1911s welded together, this exotic abomination fires two bullets per trigger pull."
-- L["wep." .. w .. ".desc.quote"] = "\"If the 1911 is so good, why isn't there a 1911 2?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Arsenal Firearms"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "automag"
-- L["wep." .. w .. ".name.full"] = "Auto Mag Pistol"
-- L["wep." .. w .. ".name"] = "Auto Mag"
-- L["wep." .. w .. ".desc"] = "Highly accurate magnum pistol. Great handling due to its size, but can only mount pistol optics."
-- L["wep." .. w .. ".desc.quote"] = "\"And if properly used, it can remove the fingerprints.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Auto Mag Corporation"
-- L["wep." .. w .. ".credits"] = "Model: RedRogueXIII \nTextures/Sounds: Futon \nAnimations: Tactical Intervention"

w = ws .. "chinalake"
-- L["wep." .. w .. ".name.full"] = "China Lake Launcher"
-- L["wep." .. w .. ".name"] = "China Lake"
-- L["wep." .. w .. ".desc"] = "Heavy pump action grenade launcher with high muzzle velocity but poor handling."
-- L["wep." .. w .. ".desc.quote"] = "Only 59 of these ever existed. Where'd you get this one?"
-- L["wep." .. w .. ".trivia.manufacturer"] = "NAWS China Lake"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "coltsmg"
-- L["wep." .. w .. ".name"] = "Colt 9mm SMG"
-- L["wep." .. w .. ".desc"] = "AR platform burst-fire SMG. Excellent recoil control, good damage and range but limited optic options. Favored by the Department of Energy."
-- L["wep." .. w .. ".desc.quote"] = "Loudspeaker not included."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Assets: Twinke Masta & Kimono \nSounds: Strelok & New World Interactive \nAnimations: Tactical Intervention"

w = ws .. "cx4"
-- L["wep." .. w .. ".name.full"] = "Beretta CX4 Storm"
-- L["wep." .. w .. ".name"] = "CX4 Storm"
-- L["wep." .. w .. ".desc"] = "Semi-automatic pistol carbine with good range. \nMediocre armor penetration, but the large frame makes the weapon quite stable."
-- L["wep." .. w .. ".desc.quote"] = "As famously seen in a certain PMC leader's arsenal."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "degala"
-- L["wep." .. w .. ".name.full"] = "Desert Eagle"
-- L["wep." .. w .. ".name"] = "Deagle"
-- L["wep." .. w .. ".desc"] = "Imposing magnum pistol, as iconic as it gets. \nPowerful and high capacity, but recoil is hard to manage."
-- L["wep." .. w .. ".desc.quote"] = "\"You hear that, Mr. Anderson?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Magnum Research"
-- L["wep." .. w .. ".credits"] = "Model: Vashts1985 \nTextures: Racer445 \nSounds:Vunsunta, XLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "fiveseven"
-- L["wep." .. w .. ".name.full"] = "FN Five-seveN"
-- L["wep." .. w .. ".name"] = "Five-seveN"
-- L["wep." .. w .. ".desc"] = "Bulky PDW caliber pistol with excellent capacity. \nHigh velocity rounds retain effectiveness at range and pierces armor easily."
-- L["wep." .. w .. ".desc.quote"] = "Is that a ferret running around?"
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2, edited by speedonerd \nSounds: Vunsunta, Counter-Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "fnc"
-- L["wep." .. w .. ".name.full"] = "FN FNC Para"
-- L["wep." .. w .. ".name"] = "FNC Para"
-- L["wep." .. w .. ".desc"] = "Lightweight assault rifle with high hipfire precision and mobility, but low range and poor armor penetration."
-- L["wep." .. w .. ".desc.quote"] = "\"I say what I mean and I do what I say.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Twinke Masta, the_tub,  Xero \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "glock18"
-- L["wep." .. w .. ".name"] = "Glock 18C"
-- L["wep." .. w .. ".desc"] = "Machine pistol with high fire rate and mobility."
-- L["wep." .. w .. ".desc.quote"] = "\"Sooner or later, you'll have to jump.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Glock Ges.m.b.H"
-- L["wep." .. w .. ".credits"] = "Model: Hav0k101 \nTextures: el maestro de graffiti \nSounds: BlitzBoaR, Lorn, Ghost597879, Zeven II \nAnimations: Tactical Intervention"

w = ws .. "k98"
-- L["wep." .. w .. ".name.full"] = "Karabiner 98k"
-- L["wep." .. w .. ".name"] = "Kar98k"
-- L["wep." .. w .. ".desc"] = "Antique bolt-action rifle with an enduring design. Powerful up close, but is essentially obsolete on the modern battlefield."
-- L["wep." .. w .. ".desc.quote"] = "\"Do you want total war?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Mauser"
-- L["wep." .. w .. ".credits"] = "Model: Day of Defeat: Source, edited by 8Z \nTextures: Cafe Rev., rascal, 5hifty \nSounds: rzen1th \nAnimations Cry of Fear, Lazarus"

w = ws .. "k98_varmint"
-- L["wep." .. w .. ".name"] = "Varmint Rifle"
-- L["wep." .. w .. ".desc"] = "Bolt-action rifle based on the Mauser action. Accepts ubiquitous AR-15 magazines. Lightweight, easy to use and has a generous capacity, but damage is low."
-- L["wep." .. w .. ".desc.quote"] = "For rodents of... unassuming size."
-- L["wep." .. w .. ".trivia.manufacturer"] = "All-American Firearms"
-- L["wep." .. w .. ".credits"] = "Model: Day of Defeat: Source, edited by 8Z \nTextures: 5hifty \nSounds: rzen1th \nAnimations: Tactical Intervention"

w = ws .. "m14"
-- L["wep." .. w .. ".name"] = "M14 SOPMOD"
-- L["wep." .. w .. ".desc"] = "Modernized short barrel rifle with improved mobility and fast automatic fire but punishing recoil. \nEquipped with a 6x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Troy Industries"
-- L["wep." .. w .. ".credits"] = "Model: General Tso & Twinke Masta \nTextures: Thanez, Twinke Masta \nSounds: Lakedown, teh strelok & Futon \nAnimations: Tactical Intervention"

w = ws .. "m16a2"
-- L["wep." .. w .. ".name.full"] = "Colt M16A2"
-- L["wep." .. w .. ".name"] = "M16A2"
-- L["wep." .. w .. ".desc"] = "Vintage burst assault rifle with limited optic options. Despite this, its stable recoil and high damage makes it reliable at medium range."
-- L["wep." .. w .. ".desc.quote"] = "\"Take clean shots, watch your background.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta, SureShot, vagrant \nTextures: Stoke, modderfreak \nSounds: Vunsunta, Navaro \nAnimations: Tactical Intervention"

w = ws .. "m500"
-- L["wep." .. w .. ".name.full"] = "SW Model 500"
-- L["wep." .. w .. ".name"] = "M500"
-- L["wep." .. w .. ".desc"] = "Massive long barrel revolver firing a massive magnum round, reigning as the most powerful production handgun in the world."
-- L["wep." .. w .. ".desc.quote"] = "\"You dweebs just ruined a five year investigation!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
-- L["wep." .. w .. ".credits"] = "Assets: Alliance of Valiant Arms \nOriginally ported to CS 1.6 by GR_Lucia \nSounds: Ghost597879, MSKyuuni & Zira \nAnimations: Tactical Intervention"

w = ws .. "mx4"
-- L["wep." .. w .. ".name.full"] = "Beretta MX4 Storm"
-- L["wep." .. w .. ".name"] = "MX4 Storm"
-- L["wep." .. w .. ".desc"] = "Bulky pistol carbine with high rate of fire but mediocre armor penetration."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "p226"
-- L["wep." .. w .. ".name.full"] = "SIG P226"
-- L["wep." .. w .. ".name"] = "P226"
-- L["wep." .. w .. ".desc"] = "Handgun with superior range and precision but low capacity."
-- L["wep." .. w .. ".desc.quote"] = "\"The correct term is 'babes,' sir.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Model: SoulSlayer \nTextures: Thanez \nSounds: Anders, DMG, FxDarkloki, & Thanez \nAnimations: Tactical Intervention"

w = ws .. "rpk"
-- L["wep." .. w .. ".name"] = "RPK"
-- L["wep." .. w .. ".desc"] = "Light machine gun derived from an infantry rifle. High damage and good recoil, but mobility and spread is poor."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Molot"
-- L["wep." .. w .. ".credits"] = "Assets: Call To Arms \nAnimations: Tactical Intervention"

w = ws .. "ruger"
-- L["wep." .. w .. ".name.full"] = "AMC Amphibian Ruger"
-- L["wep." .. w .. ".name"] = "Amphibian"
-- L["wep." .. w .. ".desc"] = "Small caliber pistol fitted with an integrated suppressor. Near-zero recoil due to weak rounds."
-- L["wep." .. w .. ".desc.quote"] = "\"Take comfort in knowing you never had a choice.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Sturm, Ruger & Co."
-- L["wep." .. w .. ".credits"] = "Model: The Lama \nTextures: The Miller \nAnimations: Tactical Intervention"

w = ws .. "saiga"
-- L["wep." .. w .. ".name"] = "Saiga-12K"
-- L["wep." .. w .. ".desc"] = "High capacity shotgun feeding from a box magazine, suitable for spraying down a room."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Kalashnikov Concern"
-- L["wep." .. w .. ".credits"] = "Assets: Battlefield 3 \nAnimations: Tactical Intervention"

w = ws .. "scarh"
-- L["wep." .. w .. ".name.full"] = "FN SCAR-H CQC"
-- L["wep." .. w .. ".name"] = "SCAR-H"
-- L["wep." .. w .. ".desc"] = "Compact, high mobility battle rifle with swift handling."
-- L["wep." .. w .. ".desc.quote"] = "\"Sand Bravo, we're reading 70 bogeys in your sector.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN America"
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2, edited by speedonerd \nAnimations: Tactical Intervention"

w = ws .. "sg550"
-- L["wep." .. w .. ".name.full"] = "SIG SG 550-1 Sniper"
-- L["wep." .. w .. ".name"] = "SG 550-1"
-- L["wep." .. w .. ".desc"] = "Carbine caliber marksman rifle with fast automatic fire. Easy to control in short bursts and has high armor penetration. Equipped with a 6x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c & Twinke Masta \nTextures: Twinke Masta \nSounds: Farion, Treyarch & Tactical Intervention \nAnimations: Tactical Intervention"

w = ws .. "sg550r"
-- L["wep." .. w .. ".name.full"] = "SIG SG550-2 SP"
-- L["wep." .. w .. ".name"] = "SG 550-2"
-- L["wep." .. w .. ".desc"] = "Long barrel rifle converted to semi-automatic for civilian markets. Easy to control and has high armor penetration."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c & Twinke Masta \nTextures: Twinke Masta \nSounds: Farion, Treyarch & Tactical Intervention \nAnimations: Tactical Intervention"

w = ws .. "sl8"
-- L["wep." .. w .. ".name.full"] = "HK SL8"
-- L["wep." .. w .. ".name"] = "SL8"
-- L["wep." .. w .. ".desc"] = "Semi-automatic variant of the G36 made for precision shooting. Low fire rate, but recoil control is excellent. \nEquipped with a 2x scope but has no ironsight option."
-- L["wep." .. w .. ".desc.quote"] = "\"Used to be a cop myself, only for one day though.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c \nTextures: Twinke Masta \nSounds: KingFriday \nAnimations: Tactical Intervention"

w = ws .. "star15"
-- L["wep." .. w .. ".name.full"] = "Spikes Tactical AR-15"
-- L["wep." .. w .. ".name"] = "ST AR-15"
-- L["wep." .. w .. ".desc"] = "Aftermarket AR-15 fine tuned for precision shooting. \nEver the choice for lone wolves on a path of revenge, your fate will be a cacophonous funeral... and a silent farewell. Bring a detonator."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Spikes Tactical"
-- L["wep." .. w .. ".credits"] = "Assets: carl ruins everything, Leon-DLL, Mira + various sources \nSounds: Insurgency, rzen1th & Tactical Intervention \nAnimations: Tactical Intervention"

w = ws .. "t850"
-- L["wep." .. w .. ".name.full"] = "Taurus 850 Ultralite"
-- L["wep." .. w .. ".name"] = "T850"
-- L["wep." .. w .. ".desc"] = "Snub-nosed revolver with compact form factor. Lethality falls off sharply past point blank."
-- L["wep." .. w .. ".desc.quote"] = "Cardio is free when you're chasing gangsters."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Taurus"
-- L["wep." .. w .. ".credits"] = "Model: Fearfisch \nTextures: Millenia \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "tec9"
-- L["wep." .. w .. ".name.full"] = "Intratec TEC-9"
-- L["wep." .. w .. ".name"] = "TEC-9"
-- L["wep." .. w .. ".desc"] = "Machine pistol notorious for its ease of conversion to fully automatic fire, and subsequent criminal usage."
-- L["wep." .. w .. ".desc.quote"] = "\"The customer is always right.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Intratec"
-- L["wep." .. w .. ".credits"] = "Model/Texture: Payday 2 \nSounds: The_AntiPirate \nAnimations: Tactical Intervention"

w = ws .. "trg42"
-- L["wep." .. w .. ".name.full"] = "Sako TRG-42"
-- L["wep." .. w .. ".name"] = "TRG-42"
-- L["wep." .. w .. ".desc"] = "Magnum sniper rifle with decent handling and mobility. \nPowerful, but slow to cycle and not very stable. \nEquipped with a 12x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SAKO"
-- L["wep." .. w .. ".credits"] = "Model: Darkstorn \nTextures: SilentAssassin12 \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "usc"
-- L["wep." .. w .. ".name.full"] = "HK USC"
-- L["wep." .. w .. ".name"] = "USC"
-- L["wep." .. w .. ".desc"] = "Semi-automatic carbine variant of the UMP. Uses low capacity magazines, but its long barrel and gripstock assembly provides excellent medium range performance."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Twinke Masta, xLongWayHome, Stoke, Teh Snake & Millenia etc. \nAnimations: Tactical Intervention"

w = ws .. "val"
-- L["wep." .. w .. ".name"] = "AS Val"
-- L["wep." .. w .. ".desc"] = "Integrally-suppressed rifle with high damage output and precision, but performs poorly over long bursts."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
-- L["wep." .. w .. ".credits"] = "Model & Textures: S.T.A.L.K.E.R. \nSounds: S.T.A.L.K.E.R. & Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "vp70"
-- L["wep." .. w .. ".name.full"] = "HK VP70"
-- L["wep." .. w .. ".name"] = "VP70"
-- L["wep." .. w .. ".desc"] = "Polymer pistol with an innovative holster stock that allows for incredibly fast burst fire."
-- L["wep." .. w .. ".desc.quote"] = "\"Where's everyone going? Bingo?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model & Textures: KnechtRuprecht \nSounds: Strelok & xLongWayHome \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "vss"
-- L["wep." .. w .. ".name.full"] = "VSS Vintorez"
-- L["wep." .. w .. ".name"] = "Vintorez"
-- L["wep." .. w .. ".desc"] = "Integrally-suppressed marksman rifle with high fire rate and low recoil, but performs poorly over long bursts. \nEquipped with a 6x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
-- L["wep." .. w .. ".credits"] = "Model: Ettubrutesbro, Millenia & Twinke Masta \nTextures: Millenia \nSounds: S.T.A.L.K.E.R. & Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "xm8car"
-- L["wep." .. w .. ".name.full"] = "HK XM8 Compact"
-- L["wep." .. w .. ".name"] = "XM8 Compact"
-- L["wep." .. w .. ".desc"] = "Experimental multi-purpose carbine. Easy to use, but low damage. \nHas an adjustable integrated 2-8x scope."
-- L["wep." .. w .. ".desc.quote"] = "\"Who loves spaghetti?!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: End Of Days \nTextures: Copkiller, Twinke Masta & Wangchung \nAnimations: Tactical Intervention"

w = ws .. "xm8lmg"
-- L["wep." .. w .. ".name.full"] = "HK XM8 LMG"
-- L["wep." .. w .. ".name"] = "XM8 LMG"
-- L["wep." .. w .. ".desc"] = "Experimental multi-purpose carbine in MG configuration. Light, high capacity and low recoil, but damage is poor. \nHas an adjustable integrated 2-8x scope."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: End Of Days \nTextures: Copkiller, Twinke Masta & Wangchung \nAnimations: Tactical Intervention"

-- Attachments (interops)
L["att.ammo_star15_300blk.name.full"] = "ST AR-15 .300 AAC Blackout 改装套件"
L["att.ammo_star15_300blk.name"] = ".300 BLK"
L["att.ammo_star15_300blk.desc"] = "装填低速但近距离效果更好的弹药。"

L["att.ammo_star15_50beo.name.full"] = "ST AR-15 .50 Beowulf 改装套件"
L["att.ammo_star15_50beo.name"] = ".50 BEO"
L["att.ammo_star15_50beo.desc"] = "装填低容量高伤害的马格南弹药。"

L["att.bolt_af2011_alt.name.full"] = "AF2011-A1 交替枪管"
L["att.bolt_af2011_alt.name"] = "交替"
L["att.bolt_af2011_alt.desc"] = "交替使用两根枪管。"

L["att.muzz_comp_io_m14.desc"] = "att.muzz_pistol_comp.desc"

L["att.muzz_tec9_shroud.name.full"] = "TEC-9 枪管护照"
L["att.muzz_tec9_shroud.name"] = ".300 护罩"
L["att.muzz_tec9_shroud.desc"] = "加长枪管提升中距离性能。"

L["att.optic_ak_pso1.name.full"] = "PSO-1 瞄准镜"
L["att.optic_ak_pso1.name"] = "PSO-1"
L["att.optic_ak_pso1.desc"] = "中远距离倍率的光学准镜，部分华约枪械可用。"

L["att.optic_ar_colt.name.full"] = "柯尔特 3x20 枪镜"
L["att.optic_ar_colt.name"] = "柯尔特 3x20"
L["att.optic_ar_colt.desc"] = "低倍率光学准镜，部分 AR 型号枪械可用。"

L["att.optic_k98_zf42.name.full"] = "寨斯 6x36 枪镜"
L["att.optic_k98_zf42.name"] = "寨斯"
L["att.optic_k98_zf42.desc"] = "Kar98k 专用的中倍光学准镜。"

L["att.optic_xm8_4x.name.full"] = "XM8 内置准镜（4倍）"
L["att.optic_xm8_4x.name"] = "4x"
L["att.optic_xm8_4x.desc"] = "中距离倍率，使用 ACOG 准心。"

L["att.optic_xm8_6x.name.full"] = "XM8 内置准镜（6倍）"
L["att.optic_xm8_6x.name"] = "6x"
L["att.optic_xm8_6x.desc"] = "中远距离倍率，使用短点准心。"

L["att.optic_xm8_8x.name.full"] = "XM8 内置准镜（8倍）"
L["att.optic_xm8_8x.name"] = "8x"
L["att.optic_xm8_8x.desc"] = "远距离倍率，使用狙击准心。"

L["att.trigger_vp70_auto.name.full"] = "VP-70 自动枪托"
L["att.trigger_vp70_auto.name"] = "自动"
L["att.trigger_vp70_auto.desc"] = "用这个把 H&K 的工程师气到口吐白沫。"

L["att.trigger_vp70_semi.name.full"] = "VP-70 无枪托"
L["att.trigger_vp70_semi.name"] = "无枪托"
L["att.trigger_vp70_semi.desc"] = "摘下枪托失去三连发功能，但提升机动性和操作速度。"

///////////////////// -- [[ ArmaLite Revolution ]] --
-- Weapons
ws = "tacrp_ar_"
w = ws .. "ar15pistol"
-- L["wep." .. w .. ".name"] = "AR-15 Compact"
-- L["wep." .. w .. ".desc"] = "Stockless, extremely short barrel AR-15 configuration. \nLegally a pistol and light enough to function as a sidearm, but it is unstable and imprecise without the form factor of a rifle."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Ultra-Tac"
-- L["wep." .. w .. ".credits"] = "Model/Textures: Mateusz Woliński, Jordan Whincup \nMagazine: Twinke Masta \nSounds: Teh Strelok, Vunsunta, xLongWayHome, CS:O2 \nAnimations: Tactical Intervention"

w = ws .. "gilboa"
-- L["wep." .. w .. ".name.full"] = "Gilboa DBR Snake"
-- L["wep." .. w .. ".name"] = "Gilboa DBR"
-- L["wep." .. w .. ".desc"] = "Unique double-barrel AR carbine. Twice the lethality as one barrel, but the design is bulky and inaccurate. \nCannot accept muzzle attachments for obvious reasons."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Silver Shadow"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "hk416"
-- L["wep." .. w .. ".name.full"] = "HK HK416"
-- L["wep." .. w .. ".name"] = "HK416"
-- L["wep." .. w .. ".desc"] = "Sleek black rifle made as a competitior to the AR-15. Accurate and low recoil at the cost of some bulk."
-- L["wep." .. w .. ".desc.quote"] = "An elite gun like this is all you need."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta, B0T, SoulSlayer \nTextures: Acid Snake, el maestro de graffiti, Antman \nSounds: Vunsunta, xLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "lr300"
-- L["wep." .. w .. ".name.full"] = "Z-M LR-300"
-- L["wep." .. w .. ".name"] = "LR-300"
-- L["wep." .. w .. ".desc"] = "AR-derived \"Light Rifle\" with a modified gas system. Offers high fire rate and range, but stability is subpar. \nThe \"300\" denotes the rifle's maximum effective range in meters."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Z-M Weapons"
-- L["wep." .. w .. ".credits"] = "Model: TheLama \nTextures: Wannabe \nSounds: NightmareMutant \nAnimations: Tactical Intervention"

w = ws .. "m16a1"
-- L["wep." .. w .. ".name.full"] = "Colt M16A1"
-- L["wep." .. w .. ".name"] = "M16A1"
-- L["wep." .. w .. ".desc"] = "An antique rifle recovered from the rice fields. \nBoasts high firing rate and good range, though don't expect this bucket of rust to run without a hitch or two."
-- L["wep." .. w .. ".desc.quote"] = "Welcome to the jungle."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c \nTextures: Millenia \nCompile: The_AntiPirate \nAnimations: Tactical Intervention"

w = ws .. "m16a4"
-- L["wep." .. w .. ".name.full"] = "Colt M16A4"
-- L["wep." .. w .. ".name"] = "M16A4"
-- L["wep." .. w .. ".desc"] = "Modern infantry rifle with modern afforances like a top rail and RIS handguard. A well-rounded infantry weapon with good effective range."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta, SureShot, vagrant \nTextures: Stoke, modderfreak \nSounds: Vunsunta, Navaro \nAnimations: Tactical Intervention"

w = ws .. "sr25"
-- L["wep." .. w .. ".name.full"] = "KAC SR-25 EMR"
-- L["wep." .. w .. ".name"] = "SR-25"
-- L["wep." .. w .. ".desc"] = "\"Enhanced Match Rifle\" made for precision shooting. \nLow capacity, but otherwise has excellent performance. \nEquipped with a 10x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Knight's Armament"
-- L["wep." .. w .. ".credits"] = "Assets: Firearms: Source \nAnimations: Tactical Intervention"

w = ws .. "vltor"
-- L["wep." .. w .. ".name"] = "VLTOR SBR"
-- L["wep." .. w .. ".desc"] = "AR pattern carbine with a unique piggyback-style handguard. Excels at close range without giving up mid-range performance."
-- L["wep." .. w .. ".desc.quote"] = "\"Hustle up! Get to Whiskey Hotel!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "VLTOR"
-- L["wep." .. w .. ".credits"] = "Model/Textures: Kimono \nSounds: Teh Strelok \nAnimations: Tactical Intervention"

-- Attachments (ar)
-- L["att.bolt_gilboa_alt.name.full"] = "Gilboa DBR Alternating Bolt"
-- L["att.bolt_gilboa_alt.name"] = "Alternating"
-- L["att.bolt_gilboa_alt.desc"] = "Separated bolts that are able to fire alternatingly, somehow."

-- L["att.muzz_sr25.name.full"] = "SR-25 Suppressor Shroud"
-- L["att.muzz_sr25.name"] = "SR-25 Supp."
-- L["att.muzz_sr25.desc"] = "Unique suppressor shroud that improves ballistics but lowers fire rate."

///////////////////// -- [[ Special Delivery ]] --
-- Weapons
ws = "tacrp_sd_"
w = ws .. "1022"
-- L["wep." .. w .. ".name.full"] = "Ruger 10/22"
-- L["wep." .. w .. ".name"] = "10/22"
-- L["wep." .. w .. ".desc"] = "Ultra-lightweight plinking rifle. Highly accurate and easy to handle, but is barely lethal unless scoring a headshot."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Sturm, Ruger & Co."
-- L["wep." .. w .. ".credits"] = "Assets: No More Room in Hell \nAnimations: Tactical Intervention"

w = ws .. "1858"
-- L["wep." .. w .. ".name.full"] = "Remington 1858 Army"
-- L["wep." .. w .. ".name"] = "Army"
-- L["wep." .. w .. ".desc"] = "Antique percussion revolver packing a punch up close, but is terribly slow to shoot. Suitable for cowboy roleplay."
-- L["wep." .. w .. ".desc.quote"] = "\"Pass the whiskey!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Remington Arms"
-- L["wep." .. w .. ".credits"] = "Assets: Nimrod Hempel (Fistful of Frags) \nAnimations: CyloWalker \nQuickthrow & melee animations: speedonerd"

w = ws .. "aac_hb"
-- L["wep." .. w .. ".name.full"] = "AAC Honey Badger"
-- L["wep." .. w .. ".name"] = "Honey Badger"
-- L["wep." .. w .. ".desc"] = "A lightweight assault rifle with an integral suppressor. Powerful in close quarters and has no visible tracer, but has poor performance at range."
-- L["wep." .. w .. ".trivia.manufacturer"] = "AAC"
-- L["wep." .. w .. ".credits"] = "Model: Hyper \nAnimations: Tactical Intervention"

w = ws .. "bizon"
-- L["wep." .. w .. ".name.full"] = "PP-19 Bizon"
-- L["wep." .. w .. ".name"] = "Bizon"
-- L["wep." .. w .. ".desc"] = "AK-derrivative SMG with a high-capacity helical magazine.  Pretty weak but easy to control and handle."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Izhmash"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Milo \nSounds: Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "contender"
-- L["wep." .. w .. ".name.full"] = "T/C G2 Contender"
-- L["wep." .. w .. ".name"] = "Contender"
-- L["wep." .. w .. ".desc"] = "Single-shot hunting pistol. Accurate, compact and lethal, so you better make that one round count. \nEquipped with a 6x scope by default."
-- L["wep." .. w .. ".desc.quote"] = "\"You know what I hate? Two groups of people...\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Thompson/Center"
-- L["wep." .. w .. ".credits"] = "Model: kriboez, Doktor haus \nTextures: cR45h, syncing, tenoyl, Ultimately \nSounds: Doktor haus \nAnimations: 8Z, speedonerd"

w = ws .. "db"
-- L["wep." .. w .. ".name.full"] = "Stoeger Double Defense"
-- L["wep." .. w .. ".name"] = "Double Defense"
-- L["wep." .. w .. ".desc"] = "Modern-production short double-barrel shotgun.  Easy to handle, reliable and deadly in close quarters."
-- L["wep." .. w .. ".desc.quote"] = "\"The only thing they fear, is you.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Stoeger"
-- L["wep." .. w .. ".credits"] = "Model: Counter-Strike: Online 2 \nSounds: Navaro & Vunsunta \nAnimations: speedonerd & 8Z"

w = ws .. "delisle"
-- L["wep." .. w .. ".name.full"] = "De Lisle Carbine"
-- L["wep." .. w .. ".name"] = "De Lisle"
-- L["wep." .. w .. ".desc"] = "Pistol caliber bolt-action carbine with an integrated suppressor. One of the quietest firearms ever made, its subsonic rounds have no tracer but travel slowly."
-- L["wep." .. w .. ".desc.quote"] = "Fired into the River Thames, not a soul heard it."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Sterling Armaments"
-- L["wep." .. w .. ".credits"] = "Model: RedRougeXIII \nTextures: Storm (lovingly fixed by Unselles) \nAnimations: Tactical Intervention"

w = ws .. "dual_1911"
-- L["wep." .. w .. ".name"] = "Dueling Wyverns"
-- L["wep." .. w .. ".desc"] = "A pair of gaudy, custom made golden M1911 pistols complete with wyvern-engraved grip. Hits hard, but its low capacity can be hurting."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Springfield Armory"
-- L["wep." .. w .. ".credits"] = "Model: Schmung \nTextures: Millenia \nAnimations: Tactical Intervention"

w = ws .. "dual_degala"
-- L["wep." .. w .. ".name"] = "Dual Eagles"
-- L["wep." .. w .. ".desc"] = "Pair of gaudy gold-coated Desert Eagles, as if one wasn't enough. \nTwice the insane firepower, twice the insane recoil."
-- L["wep." .. w .. ".desc.quote"] = "\"My blood...on their hands.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Magnum Research"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c & Stoke \nTextures: The_Tub & Stoke \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "dual_ppk"
-- L["wep." .. w .. ".name"] = "Dual Agents"
-- L["wep." .. w .. ".desc"] = "A pair of suppressed PPK pistols. Swift and accurate, but the low capacity and mediocre damage demands a sharp eye and trigger discpline."
-- L["wep." .. w .. ".desc.quote"] = "You better not be picking Oddjob."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Kimono \nSounds: HK & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "dual_usp"
-- L["wep." .. w .. ".name"] = "Dual Matches"
-- L["wep." .. w .. ".desc"] = "Pair of pistols pilfered from a pair of dead metrocops. Decent damage and capacity but hefty and slow to fire."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: Silvio Dante & Twinke Masta \nTextures: LoneWolf \nAnimations: Tactical Intervention"

w = ws .. "dual_uzis"
-- L["wep." .. w .. ".name"] = "Dual Uzis"
-- L["wep." .. w .. ".desc"] = "Pair of full-auto Micro Uzis. I don't know how you expect to hit anything with this getup, but you do you I guess."
-- L["wep." .. w .. ".desc.quote"] = "\"I'll hit you with so many rights you'll be begging for a left!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Israel Military Industries"
-- L["wep." .. w .. ".credits"] = "Model: BrainBread 2 \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "dualies"
-- L["wep." .. w .. ".name"] = "Dueling Dragons"
-- L["wep." .. w .. ".desc"] = "Pair of customized pistols with a two-tone finish and dragons emblazoned on the grips.  Swift handling and decent recoil control but low stopping power."
-- L["wep." .. w .. ".desc.quote"] = "\"I released my finger from the trigger, and it was over.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
-- L["wep." .. w .. ".credits"] = "Model: Spydr \nTextures: NCFurious \nAnimations: Tactical Intervention"

w = ws .. "famas"
-- L["wep." .. w .. ".name"] = "FAMAS F1"
-- L["wep." .. w .. ".desc"] = "Burst-fire bullpup used by the French Army. High rate of fire and great accuracy is limited only by its substandard magazine capacity and pretty intense recoil. \nHas a bipod for esoteric French reasons."
-- L["wep." .. w .. ".trivia.manufacturer"] = "GIAT Industries"
-- L["wep." .. w .. ".credits"] = "Model: SnipaMasta \nTextures: SnipaMasta, Fnuxray \nAnimations: speedonerd"

w = ws .. "famas_g2"
-- L["wep." .. w .. ".name"] = "FAMAS G2"
-- L["wep." .. w .. ".desc"] = "Bullpup rifle with a blazing fast firerate, used by the French Navy. While capable of automatic fire, using burst-fire or the built-in bipod is recommended."
-- L["wep." .. w .. ".desc.quote"] = "\"God's got a sense of humor, alright.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "GIAT Industries"
-- L["wep." .. w .. ".credits"] = "Model: SnipaMasta \nTextures: SnipaMasta, Fnuxray \nAnimations: speedonerd"

w = ws .. "g3"
-- L["wep." .. w .. ".name.full"] = "HK G3A3"
-- L["wep." .. w .. ".name"] = "G3A3"
-- L["wep." .. w .. ".desc"] = "Precise heavy battle rifle with a somewhat managable automatic firemode but slow handling."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Firearms: Source \nSounds: Nightmare Mutant & FA:S2 \nAnimations: Tactical Intervention"

w = ws .. "groza"
-- L["wep." .. w .. ".name.full"] = "OTs-14 \"Groza\""
-- L["wep." .. w .. ".name"] = "Groza-4"
-- L["wep." .. w .. ".desc"] = "Integrally-suppressed bullpup made from a reconfigured AK. Weak, but has great handling and stability and has no visible tracers."
-- L["wep." .. w .. ".desc.quote"] = "\"Get out of here, Stalker.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "TsKIB SOO"
-- L["wep." .. w .. ".credits"] = "Model: Teh Snake, edited by speedonerd \nTextures: Teh Snake \nSounds: Teh Snake & speedonerd \nAnimations: speedonerd"

w = ws .. "gyrojet"
-- L["wep." .. w .. ".name.full"] = "MBA Gyrojet"
-- L["wep." .. w .. ".name"] = "Gyrojet"
-- L["wep." .. w .. ".desc"] = "Experimental weapon firing self-propelled mini-rockets. While they are powerful, the rounds are prone to failure."
-- L["wep." .. w .. ".desc.quote"] = "\"I wonder how much his remains would go for on Ebay.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "MBAssociates"
-- L["wep." .. w .. ".credits"] = "Model & Textures: RedRougeXIII \nSounds: speedonerd, Tactical Intervention \nAnimations: speedonerd"

w = ws .. "m1carbine"
-- L["wep." .. w .. ".name"] = "M1 Carbine"
-- L["wep." .. w .. ".desc"] = "WW2-era semi-auto carbine. Intended as a defensive weapon for support troops, it is accurate and lightweight but has mediocre power."
-- L["wep." .. w .. ".desc.quote"] = "\"Flash.\" \"Thunder.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "General Motors"
-- L["wep." .. w .. ".credits"] = "Model & Textures: KnechtRuprecht \nSounds: NightmareMutant \nAnimations: Tactical Intervention"

w = ws .. "mp40"
-- L["wep." .. w .. ".name.full"] = "Steyr MP40"
-- L["wep." .. w .. ".name"] = "MP40"
-- L["wep." .. w .. ".desc"] = "WW2-era SMG with a low rate of fire and light recoil. Despite its age, it still shows up in many warzones today."
-- L["wep." .. w .. ".desc.quote"] = "\"Hans, your coffee sucks. I'm not drinking that crap.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Steyr-Mannlicher"
-- L["wep." .. w .. ".credits"] = "Model: Soul-Slayer \nTextures: Kimono \nSounds: Futon & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "pkm"
-- L["wep." .. w .. ".name"] = "PKM"
-- L["wep." .. w .. ".desc"] = "General-purpose machine gun capable of intense suppressive fire. High capacity and damage but is very, very bulky."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Degtyaryov Plant"
-- L["wep." .. w .. ".credits"] = "Assets: Call to Arms \nSounds: NightmareMutant & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "ppk"
-- L["wep." .. w .. ".name.full"] = "Walther PPK"
-- L["wep." .. w .. ".name"] = "PPK"
-- L["wep." .. w .. ".desc"] = "Compact, low-capacity pocket pistol made famous by the movies. Best suited for close range self defense."
-- L["wep." .. w .. ".desc.quote"] = "\"Shocking. Positively shocking.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Kimono \nSounds: HK & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "superx3"
-- L["wep." .. w .. ".name.full"] = "Winchester Super X3"
-- L["wep." .. w .. ".name"] = "Super X3"
-- L["wep." .. w .. ".desc"] = "Civilian sporting shotgun engineered for performance. Long barrel and competition choke offer great accuracy and range but poor handling."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Winchester Repeating Arms"
-- L["wep." .. w .. ".credits"] = "Model, Textures & Sound: No More Room in Hell \nAnimations: Tactical Intervention"

w = ws .. "thompson"
-- L["wep." .. w .. ".name.full"] = "M1A1 Thompson"
-- L["wep." .. w .. ".name"] = "Thompson"
-- L["wep." .. w .. ".desc"] = "WW2-era SMG with sturdy wooden furniture. Boasts impressive close-range firepower, but is rather heavy."
-- L["wep." .. w .. ".desc.quote"] = "\"Eat lead, jerries!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Auto-Ordnance Company"
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "tt33"
-- L["wep." .. w .. ".name.full"] = "Tokarev TT-33"
-- L["wep." .. w .. ".name"] = "TT-33"
-- L["wep." .. w .. ".desc"] = "Antique pistol from beyond the Iron Curtain. High range and penetration, but has reliability issues due to its age."
-- L["wep." .. w .. ".desc.quote"] = "\"Perhaps you would prefer to avoid the red tape?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
-- L["wep." .. w .. ".credits"] = "Model: Mr.Rifleman \nTextures: BuLL5H1T & Mr.Rifleman \nSounds: NightmareMutant \nAnimations: Tactical Intervention"

w = ws .. "vz58"
-- L["wep." .. w .. ".name.full"] = "Sa vz. 58"
-- L["wep." .. w .. ".name"] = "vz. 58"
-- L["wep." .. w .. ".desc"] = "High-damage assault rifle with excellent armor piercing capabilities, converted to semi auto for civilian markets."
-- L["wep." .. w .. ".desc.quote"] = "Despite its looks, it is definitely not an AK."
-- L["wep." .. w .. ".trivia.manufacturer"] = "CZ Uherský Brod"
-- L["wep." .. w .. ".credits"] = "Model, Textures & Sounds: No More Room in Hell \nAnimations: Tactical Intervention"

w = ws .. "wa2000"
-- L["wep." .. w .. ".name.full"] = "Walther WA 2000"
-- L["wep." .. w .. ".name"] = "WA 2000"
-- L["wep." .. w .. ".desc"] = "Elegant bullpup sniper rifle with high damage and high rate of fire. \nEquipped with a 12x scope by default."
-- L["wep." .. w .. ".desc.quote"] = "\"Names are for friends, so I don't need one.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
-- L["wep." .. w .. ".credits"] = "Assets: Alliance of Valiant Arms \nOriginally ported to CS 1.6 by GR_Lucia \nSounds: HK & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

-- Attachments (sd)
L["att.trigger_dual_uzis_semi.name.full"] = "att.trigger_semi.name.full"
L["att.trigger_dual_uzis_semi.name"] = "att.trigger_semi.name"
L["att.trigger_dual_uzis_semi.desc"] = "att.trigger_semi.desc"

L["att.tac_1858_spin.name.full"] = "左轮旋转"
L["att.tac_1858_spin.name"] = "旋转"
L["att.tac_1858_spin.desc"] = "转转武器很酷。"

L["att.optic_m1_scope.name.full"] = "M1 Carbine 3.5x24 瞄准镜"
L["att.optic_m1_scope.name"] = "3.5x 瞄准镜"
L["att.optic_m1_scope.desc"] = "专门装在 M1 Carbine 上的瞄准镜。"

L["att.optic_delisle_scope.name.full"] = "De Lisle 4x24 瞄准镜"
L["att.optic_delisle_scope.name"] = "4x 瞄准镜"
L["att.optic_delisle_scope.desc"] = "专门装在 De Lisle 上的瞄准镜。"

L["att.muzz_supp_assassin.name.full"] = "刺客消音器"
L["att.muzz_supp_assassin.name"] = "刺客消音"
L["att.muzz_supp_assassin.desc"] = "显著提升射程但难以控制的超长消音器。"

L["att.ammo_gyrojet_ratshot.name.full"] = "13mm 猎鼠迷你火箭"
L["att.ammo_gyrojet_ratshot.name"] = "猎鼠"
L["att.ammo_gyrojet_ratshot.desc"] = "就近引爆的破片迷你火箭。"

L["att.ammo_gyrojet_pipe.name.full"] = "15mm 助推榴弹"
L["att.ammo_gyrojet_pipe.name"] = "榴弹"
L["att.ammo_gyrojet_pipe.desc"] = "定时引线的重型榴弹，命中目标会直接引爆。"

L["att.ammo_gyrojet_lv.name.full"] = "11mm 低速迷你火箭"
L["att.ammo_gyrojet_lv.name"] = "低速"
L["att.ammo_gyrojet_lv.desc"] = "降低速度和大小的弹药，轨迹相对不太明显。"

L["att.ammo_gyrojet_he.name.full"] = "13mm 高爆迷你火箭"
L["att.ammo_gyrojet_he.name"] = "高爆"
L["att.ammo_gyrojet_he.desc"] = "弹头装有少量爆炸物的弹药。"

L["att.ammo_1858_45colt.name.full"] = "Remington 1858 .45 Colt 改装"
L["att.ammo_1858_45colt.name"] = ".45 Colt"
L["att.ammo_1858_45colt.desc"] = "改装发射威力更大但不太可靠的弹药。"

L["att.ammo_1858_36perc.name.full"] = "Remington 1858 .36 Percussion 改装"
L["att.ammo_1858_36perc.name"] = ".36 Percussion"
L["att.ammo_1858_36perc.desc"] = "改装发射威力较小但射程更高的弹药。"

///////////////////// -- [[ Brute Force ]] --
-- Weapons
ws = "tacrp_m_"
w = ws .. "bamaslama"
-- L["wep." .. w .. ".name"] = "Alabama Slammer"
-- L["wep." .. w .. ".desc"] = "A bowie knife named after a cocktail, featuring a serrated back edge and a bayonet mount."
-- L["wep." .. w .. ".desc.quote"] = "\"Did I say you could do that?\""
-- L["wep." .. w .. ".credits"] = "Model: Havok101 \nTextures: Millenia"

w = ws .. "bat"
-- L["wep." .. w .. ".name.full"] = "Loisville Slugger TPX"
-- L["wep." .. w .. ".name"] = "Slugger"
-- L["wep." .. w .. ".desc"] = "Aluminum baseball bat, good for hitting home runs or cracking skulls."
-- L["wep." .. w .. ".desc.quote"] = "\"Pop quiz! How long's it take to beat a moron to death?\""
-- L["wep." .. w .. ".credits"] = "Model & Textures: Yogensia \nAnimations: Lazarus"

w = ws .. "bayonet"
-- L["wep." .. w .. ".name"] = "M9 Phrobis III"
-- L["wep." .. w .. ".desc"] = "Military standard-issue knife that can be mounted on a weapon as a bayonet. Nothing stopping you from using it like a normal knife, however."
-- L["wep." .. w .. ".credits"] = "Assets: BrainBread 2"

w = ws .. "boina"
-- L["wep." .. w .. ".name"] = "Cudeman Boina Verde"
-- L["wep." .. w .. ".desc"] = "Sturdy, oversized survival knife. \"Boina verde\" is Spanish for \"green beret,\" an attempt to market the knife as military-grade."
-- L["wep." .. w .. ".credits"] = "Model & Textures: Shortez"

w = ws .. "cleaver"
-- L["wep." .. w .. ".name"] = "Meat Cleaver"
-- L["wep." .. w .. ".desc"] = "Large, sturdy blade made for chopping meat, be that animal meat or human meat. Has innate Lifesteal."
-- L["wep." .. w .. ".credits"] = "Assets: Warface"

w = ws .. "crowbar"
-- L["wep." .. w .. ".name"] = "Crowbar"
-- L["wep." .. w .. ".desc"] = "All-purpose utility tool meant for prying things open; crates, safes, doors and humans!"
-- L["wep." .. w .. ".desc.quote"] = "\"I think you dropped this back in Black Mesa.\""
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2"

w = ws .. "css"
-- L["wep." .. w .. ".name"] = "The Classic"
-- L["wep." .. w .. ".desc"] = "A classic knife design from the 90's, before fancy patterns and ludicrous prices were all the rage."
-- L["wep." .. w .. ".desc.quote"] = "\"Alright, let's move out!\""
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Source"

w = ws .. "fasthawk"
-- L["wep." .. w .. ".name"] = "SOG Fasthawk"
-- L["wep." .. w .. ".desc"] = "Modernized tomahawk designed for combat. Aerodynamic design can be thrown far."
-- L["wep." .. w .. ".credits"] = "Model & Textures: Yogensia"

w = ws .. "gerber"
-- L["wep." .. w .. ".name.full"] = "Gerber LMF Infantry"
-- L["wep." .. w .. ".name"] = "LMF Infantry"
-- L["wep." .. w .. ".desc"] = "Compact knife for survival situations, such as gutting fish, carving wood or gutting and carving an enemy."
-- L["wep." .. w .. ".credits"] = "Model: Macaroane \nTextures: Blackfire"

w = ws .. "glock"
-- L["wep." .. w .. ".name.full"] = "Glock Feldmesser 78"
-- L["wep." .. w .. ".name"] = "Feldmesser 78"
-- L["wep." .. w .. ".desc"] = "A sturdy field knife with a firm grip, designed for use within the Austrian Jagdkommando."
-- L["wep." .. w .. ".desc.quote"] = "Yes, this is the same Glock that makes pistols."
-- L["wep." .. w .. ".credits"] = "Model: HellSpike \nTextures: Dr. Hubbler"

w = ws .. "hamma"
-- L["wep." .. w .. ".name"] = "Hammer"
-- L["wep." .. w .. ".desc"] = "Common craftsman tool for inserting nails into wood or securing objects in place."
-- L["wep." .. w .. ".desc.quote"] = "When you have a hammer, everything looks like a nail..."
-- L["wep." .. w .. ".credits"] = "Model: FearFisch & sHiBaN \nTextures: Meltdown, sHiBaN & Kitteh"

w = ws .. "harpoon"
-- L["wep." .. w .. ".name.full"] = "Extrema Ratio Harpoon"
-- L["wep." .. w .. ".name"] = "Harpoon"
-- L["wep." .. w .. ".desc"] = "Thin-bladed knife with serrations on the back edge for extra deep penetration."
-- L["wep." .. w .. ".credits"] = "Model: Warfrog \nTextures: kannoe"

w = ws .. "heathawk"
-- L["wep." .. w .. ".name"] = "Heat Hawk"
-- L["wep." .. w .. ".desc"] = "Axe-shaped MS weapon scaled down to human size.\nThe original utilizes a superheated edge that cuts through metal like butter, but this replica only has a glowing sticker attached to a metal blade."
-- L["wep." .. w .. ".credits"] = "Model & Textures: Amouro"

w = ws .. "incorp"
-- L["wep." .. w .. ".name"] = "Viper Knife"
-- L["wep." .. w .. ".desc"] = "Flashy flip knife with a premium stainless finish and woodgrain handle."
-- L["wep." .. w .. ".credits"] = "Model & Textures: Teh Snake"

w = ws .. "kitchen"
-- L["wep." .. w .. ".name"] = "Kitchen Knife"
-- L["wep." .. w .. ".desc"] = "Plain, simple kitchen knife. Easy to acquire and adequately lethal, knives like these are popular among street gangs and psychopaths. Has innate Lifesteal."
-- L["wep." .. w .. ".desc.quote"] = "Oi mate, you gotta license for that knife?"
-- L["wep." .. w .. ".credits"] = "Model: Kitteh \nTextures: Rochenback"

w = ws .. "knife3"
-- L["wep." .. w .. ".name"] = "Task Force Knife"
-- L["wep." .. w .. ".desc"] = "Oversized knife with a serrated edge and a curved handle, a bit overkill for what's supposed to be a military knife."
-- L["wep." .. w .. ".desc.quote"] = "\"MOM GET THE CAMERA!!\""
-- L["wep." .. w .. ".credits"] = "Model: Syncing \nTextures: Boba Fett"

w = ws .. "kukri"
-- L["wep." .. w .. ".name"] = "Kukri"
-- L["wep." .. w .. ".desc"] = "Short knife with a curved blade, supposedly designed as such so it hooks onto targets and inflicts maximum damage."
-- L["wep." .. w .. ".desc.quote"] = "\"Professionals have standards.\""
-- L["wep." .. w .. ".credits"] = "Model: Loyen \nTextures: Pain_Agent"

w = ws .. "machete"
-- L["wep." .. w .. ".name"] = "Machete"
-- L["wep." .. w .. ".desc"] = "Versatile blade that can be used as an agricultural tool, a weapon of war or as a navigational aid when deep in the bush."
-- L["wep." .. w .. ".credits"] = "Assets: BrainBread 2"

w = ws .. "pan"
-- L["wep." .. w .. ".name"] = "Frying Pan"
-- L["wep." .. w .. ".desc"] = "Stovetop cooking device made of solid cast-iron. Made iconic as a weapon through slapstick and cartoons."
-- L["wep." .. w .. ".credits"] = "Assets: Left 4 Dead 2"

w = ws .. "pipe"
-- L["wep." .. w .. ".name"] = "Lead Pipe"
-- L["wep." .. w .. ".desc"] = "Sturdy lead water pipe. Despite not being designed for any kind of harm-doing, hitting someone with it does quite a lot of harm."
-- L["wep." .. w .. ".desc.quote"] = "\"OH SHIT!! Too late!!\""
-- L["wep." .. w .. ".credits"] = "Assets: No More Room in Hell"

w = ws .. "rambo"
-- L["wep." .. w .. ".name"] = "Bowie Knife"
-- L["wep." .. w .. ".desc"] = "A classic knife design made specifically for dueling, back when knife fights were a form of entertainment. \nRemains popular due to its association with overly-masculine 80's action movie stars."
-- L["wep." .. w .. ".credits"] = "Model: fallschirmjager \nTextures: HellSpike & EinHain"

w = ws .. "shovel"
-- L["wep." .. w .. ".name"] = "Shovel"
-- L["wep." .. w .. ".desc"] = "An old army shovel, designed to quickly dig trenches. Works great as a crude melee weapon, having both a blunt face and a sharp edge."
-- L["wep." .. w .. ".desc.quote"] = "\"Maggots!\""
-- L["wep." .. w .. ".credits"] = "Assets: Day of Defeat: Source"

w = ws .. "tonfa"
-- L["wep." .. w .. ".name"] = "Police Baton"
-- L["wep." .. w .. ".desc"] = "Specialized police baton with an angled handle for an alternative grip. Useful for putting down riots in failing \"democratic\" nations."
-- L["wep." .. w .. ".credits"] = "Assets: Left 4 Dead 2"

w = ws .. "tracker"
-- L["wep." .. w .. ".name"] = "Tracker Knife"
-- L["wep." .. w .. ".desc"] = "Oversized gut knife designed for multiple hunting utilities, one of which is, conveniently, slicing open human targets."
-- L["wep." .. w .. ".credits"] = "Model: Cartman \nTextures: Henron & Fxdarkloki"

w = ws .. "wiimote"
-- L["wep." .. w .. ".name.full"] = "Nintendo Wii Remote"
-- L["wep." .. w .. ".name"] = "Wii Remote"
-- L["wep." .. w .. ".desc"] = "An iconic game controller with revolutionary motion controls. \nCareful!  Neglecting to wear the wrist strap could lead to injury."
-- L["wep." .. w .. ".desc.quote"] = "You're Out!" -- Wii Sports
-- L["wep." .. w .. ".credits"] = "Model & Textures: Mr. Pickle"

w = ws .. "wrench"
-- L["wep." .. w .. ".name"] = "Pipe Wrench"
-- L["wep." .. w .. ".desc"] = "Sturdy wrench designed for tightening water and gas pipes.  All-iron construction makes it quite the blunt weapon."
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2"

///////////////////// -- [[ Iron Curtain ]] --
-- Weapons
ws = "tacrp_ak_"
w = ws .. "aek971"
-- L["wep." .. w .. ".name"] = "AEK-971"
-- L["wep." .. w .. ".desc"] = "Experimental assault rifle using a unique dampening mechanism to reduce felt recoil. High fire rate but medicore range."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Kovrovskiy Mekhanicheskiy Zavod"
-- L["wep." .. w .. ".credits"] = "Assets: Casper, arby26 \nAnimations: Tactical Intervention"

w = ws .. "ak12"
-- L["wep." .. w .. ".name.full"] = "AK-12 Prototype"
-- L["wep." .. w .. ".name"] = "AK-12"
-- L["wep." .. w .. ".desc"] = "One of many attempts at modernizing the AK, this experimental model uses burst fire and allows for quick swapping of the weapon's caliber."
-- L["wep." .. w .. ".desc.quote"] = "The Snow Wolf's eye opens."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Kalashnikov Concern"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "ak74"
-- L["wep." .. w .. ".name"] = "AK-74"
-- L["wep." .. w .. ".desc"] = "A well-rounded staple from Eastern Europe with controllable recoil and good range. Modifications include lightweight furniture and mounts for dovetail optics."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Kalashnikov Concern"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta, TheLama \nTextures: Millenia, The Spork \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "ak74u"
-- L["wep." .. w .. ".name"] = "AKS-74U"
-- L["wep." .. w .. ".desc"] = "SMG-sized carbine designed for tank crews and special forces. Impressive firepower in a small package, but not gentle in terms of recoil."
-- L["wep." .. w .. ".desc.quote"] = "\"Mother Russia can rot, for all I care.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
-- L["wep." .. w .. ".credits"] = "Model: TheLama \nCompile: Bushmasta101 \nTextures: Thanez \nSounds: BlitzBoaR/CC5/modderfreak, .exe \nAnimations: Tactical Intervention"

w = ws .. "an94"
-- L["wep." .. w .. ".name.full"] = "AN-94 \"Abakan\""
-- L["wep." .. w .. ".name"] = "AN-94"
-- L["wep." .. w .. ".desc"] = "Experimental assault rifle with a unique 2-round \"hyperburst.\" The rifle's complex mechanism affords low recoil but is very bulky."
-- L["wep." .. w .. ".desc.quote"] = "\"Antje\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Kalashnikov Concern"
-- L["wep." .. w .. ".credits"] = "Assets: Firearms: Source \nAnimations: Tactical Intervention"

w = ws .. "galil_lmg"
-- L["wep." .. w .. ".name.full"] = "IMI Galil ARM"
-- L["wep." .. w .. ".name"] = "Galil ARM"
-- L["wep." .. w .. ".desc"] = "AK derivative in machine gun configuration.\nLightweight and fires at a brisk and controllable pace but with average stopping power."
-- L["wep." .. w .. ".desc.quote"] = "\"Well ya know, for me, the action is the juice.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Israel Military Industries"
-- L["wep." .. w .. ".credits"] = "Galil Assets: Counter Strike: Online 2 \nAccessories: Insurgency (2014), ported by Lt. Rocky \nSuppressed Sound: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "galil_sniper"
-- L["wep." .. w .. ".name.full"] = "IMI Galil Sniper"
-- L["wep." .. w .. ".name"] = "Galatz"
-- L["wep." .. w .. ".desc"] = "Israeli AK derivative in marksman rifle configuration.\nHighly controllable, but has a low firerate and average lethality."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Israel Military Industries"
-- L["wep." .. w .. ".credits"] = "Galil Assets: Counter Strike: Online 2 \nAccessories: Insurgency (2014), ported by Lt. Rocky \nSuppressed Sound: Magmacow \nAnimations: Tactical Intervention"

w = ws .. "rk95"
-- L["wep." .. w .. ".name.full"] = "Sako RK 95"
-- L["wep." .. w .. ".name"] = "RK 95"
-- L["wep." .. w .. ".desc"] = "Finnish AK derivative with high armor penetration and extended magazine."
-- L["wep." .. w .. ".desc.quote"] = "Despite its looks... Actually, this one's pretty much an AK."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SAKO"
-- L["wep." .. w .. ".credits"] = "Assets: Firearms: Source \nAnimations: Tactical Intervention"

w = ws .. "svd"
-- L["wep." .. w .. ".name.full"] = "Dragunov SVD"
-- L["wep." .. w .. ".name"] = "SVD"
-- L["wep." .. w .. ".desc"] = "Russian sniper rifle with low fire rate but great damage and recoil control. Equipped with a 6x scope by default.\nWhile superficially resembling the AK design, it is completely unrelated mechanically."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Kalashnikov Concern"
-- L["wep." .. w .. ".credits"] = "Model: Rafael De Jongh, Ettubrutesbro \nTextures: WangChung \nSounds: Ghost597879, King Friday, iFlip \nAnimations: Tactical Intervention"

-- Attachments (ak)
L["att.acc_ak74_poly.name.full"] = "AK-74 轻量部件"
L["att.acc_ak74_poly.name"] = "轻量"
L["att.acc_ak74_poly.desc"] = "使用伞兵配置，提升机动性和手感。"

L["att.ammo_ak12_762.name.full"] = "AK-12 7.62×39mm 改装套件"
L["att.ammo_ak12_762.name"] = "7.62×39mm"
L["att.ammo_ak12_762.desc"] = "装填更大口径的弹药，提高伤害和后座力。"

L["att.muzz_ak_booster.name.full"] = "6P26 助推器"
L["att.muzz_ak_booster.name"] = "助推器"
L["att.muzz_ak_booster.desc"] = "提升射速的 AK 型号枪口配件。"

L["att.muzz_ak_comp.name.full"] = "6P20 制退器"
L["att.muzz_ak_comp.name"] = "制退器"
L["att.muzz_ak_comp.desc"] = "控制后坐力的 AK 型号枪口配件。"

L["att.muzz_supp_pbs.name.full"] = "PBS-5 消音器"
L["att.muzz_supp_pbs.name"] = "PBS消音"
L["att.muzz_supp_pbs.desc"] = "提升后坐力稳定性但准度降低的东欧消音器。"

L["att.optic_ak_kobra.name.full"] = "Kobra 瞄准镜"
L["att.optic_ak_kobra.name"] = "Kobra"
L["att.optic_ak_kobra.desc"] = "低倍率反射准镜，部分华约枪械可用。"

L["att.optic_galil.name.full"] = "Nimrod 6x40 瞄准镜"
L["att.optic_galil.name"] = "Nimrod 6x40"
L["att.optic_galil.desc"] = "专门安装在 Galil 型枪械上的狙击镜。"
