L = {} -- English Content Strings

--[[
To localize an attachment (replace optic_acog with your attachment class):
L["att.optic_acog.name"] = "Attachment Name"
L["att.optic_acog.name.full"] = "Attachment Full Name"
L["att.optic_acog.desc"] = "Attachment Description"

To localize a weapon (replace tacrp_vertec with your weapon class):
L["wep.tacrp_vertec.name"] = "Weapon Name"
L["wep.tacrp_vertec.name.full"] = "Weapon Full Name"
L["wep.tacrp_vertec.desc"] = "Weapon Description"
L["wep.tacrp_vertec.desc.quote"] = "Weapon Quote" -- this is the italics line at the bottom
L["wep.tacrp_vertec.trivia.manufacturer"] = "Trivia Manufacturer"
L["wep.tacrp_vertec.trivia.year"] = "Trivia Caliber"
L["wep.tacrp_vertec.trivia.caliber"] = "Trivia Year"
]]

///////////////////// -- [[ TacRP Base ]] --
-- Weapons
local ws = "tacrp_"
local w = ws .. "ak47"
L["wep." .. w .. ".name"] = "Beryl 96"
L["wep." .. w .. ".name.full"] = "FB Beryl 96"
L["wep." .. w .. ".desc"] = "Easy to handle rifle with low fire rate and recoil."
L["wep." .. w .. ".desc.quote"] = "Despite its looks, it is not an AK."
L["wep." .. w .. ".trivia.manufacturer"] = "FB \"Łucznik\" Radom"
L["wep." .. w .. ".trivia.caliber"] = "5.56x45mm"
L["wep." .. w .. ".credits"] = "Assets: Tactical Intervention"

w = ws .. "amd65"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ar15"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "as50"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "aug"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "bekas"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "c4_detonator"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "civ_amd65"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "civ_g36k"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "civ_m320"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "civ_mp5"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "civ_p90"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "dsa58"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ex_ak47"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ex_glock"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ex_hecate"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ex_hk45c"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ex_m4a1"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ex_m1911"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ex_mac10"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ex_mp9"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ex_stinger"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ex_ump45"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ex_usp"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "fp6"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "g36k"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "gsr1911"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "hk417"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "k1a"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "knife"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "knife2"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "ks23"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "m1"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "m4"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "m4star10"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "m14"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "m320"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "medkit"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "mg4"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "mp5"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "mp7"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "mr96"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "mtx_dual"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "nade_charge"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "nade_flashbang"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "nade_frag"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "nade_gas"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "nade_heal"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "nade_smoke"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "nade_thermite"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "p90"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "p250"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "p2000"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "pdw"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "riot_shield"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "rpg7"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "sg551"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "skorpion"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "sphinx"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "spr"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "superv"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "tgs12"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "uratio"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "uzi"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "vertec"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

w = ws .. "xd45"
-- L["wep." .. w .. ".name"] = "REPLACEME"
-- L["wep." .. w .. ".name.full"] = "REPLACEME"
-- L["wep." .. w .. ".desc"] = "REPLACEME"
-- L["wep." .. w .. ".desc.quote"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.manufacturer"] = "REPLACEME"
-- L["wep." .. w .. ".trivia.caliber"] = "REPLACEME"
-- L["wep." .. w .. ".credits"] = "REPLACEME"

-- Attachments (Non-Bulk)
L["att.melee_spec_charge.name.full"] = "demoknight tf2"
L["att.melee_spec_charge.name"] = "Charge"
L["att.melee_spec_charge.desc"] = "Advance with reckless abandon, and break some laws of physics too."
L["att.pro.melee_spec_charge1"] = "RELOAD: Charge"
L["att.pro.melee_spec_charge2"] = "WALK + RELOAD: Select Charge Mode"
L["att.pro.melee_spec_charge3"] = "Reduced Damage while Charging"
L["att.pro.melee_spec_charge4"] = "Reduced Self-Damage"

L["att.melee_spec_lunge.name"] = "Frency"
L["att.melee_spec_lunge.desc"] = "Close the distance and overwhelm your enemies."
L["att.pro.melee_spec_lunge"] = "RELOAD: Lunge in Aim Direction"

L["att.melee_spec_nade.name.full"] = "Bombardier"
L["att.melee_spec_nade.name"] = "Bomber"
L["att.melee_spec_nade.desc"] = "Use jury-rigged impact grenades to ruin someone's day."
L["att.pro.melee_spec_nade1"] = "RELOAD: Toggle Grenades"
L["att.pro.melee_spec_nade2"] = "Grenades Explode on Impact"
L["att.con.melee_spec_nade"] = "Grenade Damage"

L["att.melee_spec_ninja.name"] = "Ninja"
L["att.melee_spec_ninja.desc"] = "Disrupt your enemies and strike with the element of surprise."
L["att.pro.melee_spec_ninja1"] = "RELOAD: Palm Strike / Climb"
L["att.pro.melee_spec_ninja2"] = "RELOAD: (Mid-Air + Crouch): Dive Kick"
L["att.pro.melee_spec_ninja3"] = "RELOAD: (Crouch): Backhop"
L["att.pro.melee_spec_ninja4"] = "Silent Footsteps"

L["att.melee_spec_scout.name.full"] = "jerma tf2"
L["att.melee_spec_scout.name"] = "Scout"
L["att.melee_spec_scout.desc"] = "Grass grows, sun shines, birds fly, and brotha' - I hurt people."
L["att.pro.melee_spec_scout1"] = "RELOAD: Launch Ball"
L["att.pro.melee_spec_scout2"] = "Ball Damage Scales with Distance"
L["att.pro.melee_spec_scout3"] = "Ball Applies Slow on Hit"
L["att.pro.melee_spec_scout4"] = "Multi Jump"

L["att.melee_spec_step.name"] = "Airdash"
L["att.melee_spec_step.desc"] = "Mobility tool used by blood-fueled robots and transgender women."
L["att.pro.melee_spec_step1"] = "RELOAD: Dash in Movement Direction"
L["att.pro.melee_spec_step2"] = "Invulnerable while Dashing"

L["att.melee_spec_block.name.full"] = "High Guard"
L["att.melee_spec_block.name"] = "Guard"
L["att.melee_spec_block.desc"] = "Defense is the best offense. It is, coinicidently, also the best defense."
L["att.pro.melee_spec_block1"] = "ALT-FIRE: Block Melee Attacks or Projectiles"
L["att.pro.melee_spec_block2"] = "Heavy Counterattack After Successful Block"

L["att.melee_spec_heavy.name.full"] = "Heavy-handed"
L["att.melee_spec_heavy.name"] = "Heavy"
L["att.melee_spec_heavy.desc"] = "A classic counter-terrorist technique: Just smack them real hard."
L["att.pro.melee_spec_heavy1"] = "ALT-FIRE: Heavy Attack"
L["att.pro.melee_spec_heavy2"] = "Backstab Damage"

L["att.melee_tech_nade.name.full"] = "Grenadier"
L["att.melee_tech_nade.name"] = "Grenade"
L["att.melee_tech_nade.desc"] = "Always good to have something handy to throw."
L["att.pro.melee_tech_nade1"] = "ALT-FIRE: Quickthrow"
L["att.pro.melee_tech_nade2"] = "Faster Quickthrow"
L["att.pro.melee_tech_nade3"] = "Throw Rocks"

L["att.melee_tech_throw.name.full"] = "Knife Throw"
L["att.melee_tech_throw.name"] = "Throw"
L["att.melee_tech_throw.desc"] = "Bar trick turned lethal."
L["att.pro.melee_tech_throw1"] = "ALT-FIRE: Throw Weapon"
L["att.pro.melee_tech_throw2"] = "Consumes Crossbow Bolt Ammo"
L["att.pro.melee_tech_throw3"] = "Bonus Headshot Damage"
L["att.pro.melee_tech_throw4"] = "Bonus Damage on Slowed/Stunned Targets"

-- Attachments (acc)
L["att.acc_bipod.name"] = "Bipod"
L["att.acc_bipod.desc"] = "Foldable support that stabilizes the weapon when deployed."

L["att.acc_brace.name"] = "Pistol Brace"
L["att.acc_brace.desc"] = "Turns your pistol into a rifle. The ATF is gonna get your ass."




L["att.acc_extmag.name"] = "Mag Extender"
L["att.acc_extmag.name.full"] = "Extended Magazine"
L["att.acc_extmag.desc"] = "Slightly increase weapon capacity."

L["att.ammo_shotgun_slugs.name"] = "Slugs"
L["att.ammo_shotgun_slugs.name.full"] = "Slug Shells"
L["att.ammo_shotgun_slugs.desc"] = "Fire a single projectile for medium range shooting."

L["att.ammo_shotgun_triple.name"] = "Triple Hit"
L["att.ammo_shotgun_triple.name.full"] = "Triple Hit Shells"
L["att.ammo_shotgun_triple.desc"] = "Fire three projectiles for more accuracy."

L["att.muzz_pistol_comp.name"] = "Compensator"
L["att.muzz_pistol_comp.desc"] = "Muzzle device which reduces recoil impact."

L["att.bolt_refurbished.name"] = "Refurbished"
L["att.bolt_refurbished.name.full"] = "Refurbished Bolt"
L["att.bolt_refurbished.desc"] = "Fix the gun's reliability problems with some armory tweaks."

///////////////////// -- [[ InterOps Weapons ]] --
-- Weapons

///////////////////// -- [[ ArmaLite Revolution ]] --
-- Weapons

///////////////////// -- [[ Special Delivery ]] --
-- Weapons

///////////////////// -- [[ Brute Force ]] --
-- Weapons

///////////////////// -- [[ Iron Curtain ]] --
-- Weapons

///////////////////// -- [[ Heavy Duty ]] --
-- Weapons

///////////////////// -- [[ ExoOps ]] --
-- Weapons

///////////////////// -- [[ Scavenger's Spoils ]] --
-- Weapons

///////////////////// -- [[ Danger Zone Entities ]] --
-- Weapons

///////////////////// -- [[ One-Offs ]] --
-- Weapons